import Sandpile.Walk
import Sandpile.External.GreenBoundsHigh
import Sandpile.External.GreenBoundsHighProved
import Sandpile.Support.OdometerLocalization

/-!
# Localization of the odometer by conditional expectation

Localization lemma of sandpile.tex, frozen.  `sandpile.tex:6451-6462`
(label `lem:dgt4-localization`):

  "For a finite set $K\subset\Z^d$ and $r\geq1$, write
   \[
     K_r\coloneqq \{y\in\Z^d: |y-z|\leq r\text{ for some }z\in K\}\, .
   \]
   There is $c>0$ such that, for every finite $K\subset\Z^d$, every
   $r\geq1$, every $a>0$, and every $t\in\N$,
   \[
     \P\Bigl(\max_{x\in K}\left|u_t(x)-\E\bigl[u_t(x)\mid \zeta(y), y\in K_r\bigr]\right|>a\Bigr)
     \leq 2|K|\exp\{-c\min(a^2r^{d-4}, ar^{d-2})\}\, .
   \]"

The standing hypotheses of Section `sec:dim5plus` (`sandpile.tex:4079`,
`sandpile.tex:4096-4108`) are in force: `d ≥ 5`, the scenery is i.i.d. with
`E ζ(0) = 0` and `0 < Var(ζ(0)) < ∞`, and `E e^{θ₀|ζ(0)|} ≤ K₀`.  The constant
`c` is produced by `lem:weighted-exp-conc`(b), whose constants depend only on
`θ₀` and `K₀`, together with the `d ≥ 5` Green bounds; it is therefore bound
after `d, θ₀, K₀` and before the law `ν`, so it is uniform over the class.
The scenery is the integration variable, with law `LatticeProb.iidLaw d ν`, and
`u_t` is `Sandpile.odometerOf ζ t`.
The conditional expectation `E[u_t(x) | ζ(y), y ∈ K_r]` is `MeasureTheory.condExp`
for the sigma-algebra generated by the coordinates in `K_r`, that is, the comap
sigma-algebra of the restriction map `(Site d → ℝ) → (K_r → ℝ)`; `condExp` takes
its junk value `0` only off the integrable case, and `u_t(x)` is integrable under
the exponential-moment hypothesis.
The maximum over `K` is written as an existential over `x ∈ K` so that the empty
`K` carries no junk maximum: both sides are then zero.
Probabilities are the `ℝ≥0∞`-valued measure of the event; the right-hand side is
nonnegative, so `ENNReal.ofReal` is exact there.  The event is measurable, since
`u_t(x)` depends on finitely many coordinates.

The exponential-moment bound is stated together with the integrability of the
exponential, as the paper's `K₀ < ∞` requires: the Bochner integral of a
non-integrable nonnegative function is zero, so the bound alone would hold for
every law with no exponential moment.
-/

open MeasureTheory ProbabilityTheory Filter Topology
open scoped ENNReal

namespace Sandpile.Frozen.DGT4Localization

/-- The box metric of `sandpile.tex:6366-6368`: "All distances in this
subsection are measured in the box metric used to define $Q(x,L)$; in
particular, $|x-y|$ below denotes this distance."  The box `Q(x,L)` is defined
at `sandpile.tex:680` by `\max_{1\leq i\leq d}|y_i-x_i|\leq L`. -/
def boxDist {d : ℕ} (x y : Site d) : ℕ :=
  Finset.univ.sup fun i => (x i - y i).natAbs

/-- The thickening `K_r` of `sandpile.tex:6373-6376`: "For a finite set
$K\subset\Z^d$ and $r\geq1$, write
$K_r\coloneqq \{y\in\Z^d: |y-z|\leq r\text{ for some }z\in K\}$." -/
def thickening {d : ℕ} (K : Finset (Site d)) (r : ℝ) : Set (Site d) :=
  {y | ∃ z ∈ K, (boxDist y z : ℝ) ≤ r}

end Sandpile.Frozen.DGT4Localization

-- FROZEN-STATEMENT-BEGIN
theorem Sandpile.Frozen.dgt4_localization
    (d : ℕ) (hd : 5 ≤ d) (θ₀ K₀ : ℝ) (hθ₀ : 0 < θ₀) :
    ∃ c : ℝ, 0 < c ∧ ∀ ν : Measure ℝ, IsProbabilityMeasure ν →
      ∫ z, z ∂ν = 0 → 0 < evariance id ν → evariance id ν < ⊤ →
      Integrable (fun z => Real.exp (θ₀ * |z|)) ν →
      ∫ z, Real.exp (θ₀ * |z|) ∂ν ≤ K₀ →
      ∀ (K : Finset (Sandpile.Site d)) (r a : ℝ), 1 ≤ r → 0 < a → ∀ t : ℕ,
        (LatticeProb.iidLaw d ν)
            {ζ | ∃ x ∈ K, a < |Sandpile.odometerOf ζ t x -
              (MeasureTheory.condExp
                (MeasurableSpace.comap
                  (fun ω : Sandpile.Site d → ℝ =>
                    fun y : Sandpile.Frozen.DGT4Localization.thickening K r =>
                      ω (y : Sandpile.Site d))
                  inferInstance)
                (LatticeProb.iidLaw d ν)
                (fun ω => Sandpile.odometerOf ω t x)) ζ|} ≤
          ENNReal.ofReal (2 * (K.card : ℝ) *
            Real.exp (-(c * min (a ^ 2 * r ^ ((d : ℝ) - 4)) (a * r ^ ((d : ℝ) - 2)))))
-- FROZEN-STATEMENT-END
:= by
  classical
  have hGreenHigh : Sandpile.External.GreenBoundsHigh := Sandpile.External.greenBoundsHigh
  obtain ⟨c, hc, htail⟩ := Sandpile.odometer_condExp_tail hGreenHigh hd θ₀ K₀ hθ₀
  refine ⟨c, hc, ?_⟩
  intro ν hν _hmean _hvarpos _hvarfin hexp hK K r a hr ha t
  let S := Sandpile.Frozen.DGT4Localization.thickening K r
  let E := fun x : Sandpile.Site d => {ζ : Sandpile.Site d → ℝ |
    a < |Sandpile.odometerOf ζ t x - (MeasureTheory.condExp
      (MeasurableSpace.comap (fun ω : Sandpile.Site d → ℝ => fun y : S => ω y) inferInstance)
      (LatticeProb.iidLaw d ν) (fun ω => Sandpile.odometerOf ω t x)) ζ|}
  let B := 2 * Real.exp (-(c * min (a ^ 2 * r ^ ((d : ℝ) - 4))
    (a * r ^ ((d : ℝ) - 2))))
  have hB : 0 ≤ B := by dsimp [B]; positivity
  have hx (x : Sandpile.Site d) (hx : x ∈ K) :
      (LatticeProb.iidLaw d ν) (E x) ≤ ENNReal.ofReal B := by
    exact htail ν hν hexp hK S r a hr ha.le t x (fun y hy => ⟨x, hx, hy⟩)
  calc
    _ = (LatticeProb.iidLaw d ν) (⋃ x ∈ K, E x) := by
      congr 1
      ext ζ
      simp only [Set.mem_setOf_eq, Set.mem_iUnion, E, S]
      constructor <;> rintro ⟨x, hx, h⟩ <;> exact ⟨x, hx, h⟩
    _ ≤ ∑ x ∈ K, (LatticeProb.iidLaw d ν) (E x) := measure_biUnion_finset_le K E
    _ ≤ ∑ _x ∈ K, ENNReal.ofReal B := Finset.sum_le_sum hx
    _ = _ := by
      rw [← ENNReal.ofReal_sum_of_nonneg (fun _ _ => hB), Finset.sum_const, nsmul_eq_mul]
      congr 1
      dsimp [B]
      ring
