import Mathlib.Probability.Independence.Basic
import Mathlib.Probability.Independence.Integration
import Mathlib.MeasureTheory.Measure.Tilted
import Mathlib.InformationTheory.KullbackLeibler.Basic

/-!
# Adaptive Cameron–Martin comparison for stopping sets

This file proves, in the abstract, the comparison behind Step 3 of `prop:fixed-scale-crossings`
(`sandpile.tex:2334-2400`). For an arbitrary probability space carrying a finite independent
family of sub-`σ`-algebras `G i` and a random finite index set `S` that is a stopping set for
that family (`IsIndepStoppingSet`, meaning the event `S = A` is decided by the coordinates in
`A`), the sum of the revealed coordinates `∑ i ∈ S ω, ξ i ω` has mean zero
(`integral_sum_stoppingSet_eq_zero`), tilting only the revealed coordinates and tilting every
coordinate assign the same probability to any event the exploration decides
(`tilted_cm_apply_eq_of_decided`), and the relative entropy of the adaptive tilt is exactly
`a ^ 2 / 2` times the expected number of revealed coordinates (`klDiv_tilted_cm_le`), matching
the paper's `L² 𝔼 𝒩 / (2 𝔪² R²)` bound with `a = L / (𝔪 R)`. Nothing here mentions a white
noise, a ball field, or a crossing, so the statements are stated purely in terms of an
independent family and a stopping set.
-/

open MeasureTheory ProbabilityTheory

namespace Sandpile.Support

/-- The sub-sigma-algebra generated by the coordinates indexed by `A`. -/
@[reducible] def indepAlg {Ω ι : Type*} (G : ι → MeasurableSpace Ω) (A : Set ι) :
    MeasurableSpace Ω := ⨆ i ∈ A, G i

/-- The coordinate algebra `G i` sits below the joint algebra `indepAlg G A` of a set `A`
containing `i`. -/
theorem le_indepAlg {Ω ι : Type*} (G : ι → MeasurableSpace Ω) {A : Set ι} {i : ι} (hi : i ∈ A) :
    G i ≤ indepAlg G A :=
  le_iSup₂ (f := fun i (_ : i ∈ A) => G i) i hi

/-- `indepAlg G` is monotone in the index set: enlarging `A` to `B` can only enlarge the
generated algebra. -/
theorem indepAlg_mono {Ω ι : Type*} (G : ι → MeasurableSpace Ω) {A B : Set ι} (h : A ⊆ B) :
    indepAlg G A ≤ indepAlg G B :=
  iSup₂_le fun _ hi => le_indepAlg G (h hi)

/-- `indepAlg G A` stays below any ambient `σ`-algebra `mΩ` that each `G i` sits below. -/
theorem indepAlg_le {Ω ι : Type*} {G : ι → MeasurableSpace Ω} {mΩ : MeasurableSpace Ω}
    (hle : ∀ i, G i ≤ mΩ) (A : Set ι) : indepAlg G A ≤ mΩ :=
  iSup₂_le fun i _ => hle i

/-- A finite product `∏ i ∈ B, f i` is measurable for the joint algebra `indepAlg G B` as soon
as each factor `f i` is measurable for its own coordinate algebra `G i`. -/
theorem measurable_finset_prod {Ω ι : Type*} {G : ι → MeasurableSpace Ω} (f : ι → Ω → ℝ)
    (hfm : ∀ i, Measurable[G i] (f i)) (B : Finset ι) :
    Measurable[indepAlg G (B : Set ι)] fun ω => ∏ i ∈ B, f i ω :=
  Finset.measurable_prod B fun i hi => (hfm i).mono (le_indepAlg G hi) le_rfl

variable {Ω ι : Type*} [mΩ : MeasurableSpace Ω] {P : Measure Ω}

/-- Independence of two `σ`-algebras passes down to any pair of smaller sub-algebras. -/
theorem indep_of_le {m₁ m₂ m₁' m₂' : MeasurableSpace Ω} (h : Indep m₁ m₂ P)
    (h1 : m₁' ≤ m₁) (h2 : m₂' ≤ m₂) : Indep m₁' m₂' P := by
  rw [Indep_iff] at h ⊢
  exact fun t1 t2 ht1 ht2 => h t1 t2 (h1 _ ht1) (h2 _ ht2)

/-- If the `σ`-algebras generated by `X` and by `Y` are independent, then `X` and `Y` are
independent as functions. -/
theorem indepFun_of_indep {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    {m₁ m₂ : MeasurableSpace Ω} (h : Indep m₁ m₂ P) {X : Ω → β} {Y : Ω → γ}
    (hX : Measurable[m₁] X) (hY : Measurable[m₂] Y) : IndepFun X Y P := by
  rw [IndepFun_iff_Indep, Indep_iff]
  intro t1 t2 ht1 ht2
  exact (Indep_iff m₁ m₂ P).mp h t1 t2 (hX.comap_le _ ht1) (hY.comap_le _ ht2)

/-- The joint algebras `indepAlg G A` and `indepAlg G B` of disjoint index sets `A` and `B` are
independent, for an independent family `G`. -/
theorem indep_indepAlg {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ)
    (hGindep : iIndep G P) {A B : Set ι} (hAB : Disjoint A B) :
    Indep (indepAlg G A) (indepAlg G B) P :=
  indep_iSup_of_disjoint hGle hGindep hAB

/-- A finite product `∏ i ∈ B, f i` of independent, integrable, mean-one functions is
integrable and has mean one, proved by induction on `B` using
`IndepFun.integral_fun_mul_eq_mul_integral`. -/
theorem integrable_finset_prod_and_integral [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    (f : ι → Ω → ℝ) (hfm : ∀ i, Measurable[G i] (f i)) (hfi : ∀ i, Integrable (f i) P)
    (hf1 : ∀ i, ∫ ω, f i ω ∂P = 1) (B : Finset ι) :
    Integrable (fun ω => ∏ i ∈ B, f i ω) P ∧ ∫ ω, (∏ i ∈ B, f i ω) ∂P = 1 := by
  classical
  induction B using Finset.induction_on with
  | empty => simp
  | insert j B hj ih =>
    have hdisj : Disjoint ({j} : Set ι) (B : Set ι) := by
      simpa [Set.disjoint_singleton_left] using hj
    have hind : IndepFun (f j) (fun ω => ∏ i ∈ B, f i ω) P :=
      indepFun_of_indep (indep_indepAlg hGle hGindep hdisj)
        ((hfm j).mono (le_indepAlg G (Set.mem_singleton j)) le_rfl)
        (measurable_finset_prod f hfm B)
    have hprod : ∀ ω, ∏ i ∈ insert j B, f i ω = f j ω * ∏ i ∈ B, f i ω := fun ω => by
      rw [Finset.prod_insert hj]
    refine ⟨?_, ?_⟩
    · have hmul := hind.integrable_mul (hfi j) ih.1
      refine hmul.congr ?_
      filter_upwards with ω using (hprod ω).symm
    · simp_rw [hprod]
      rw [hind.integral_fun_mul_eq_mul_integral (hfi j).aestronglyMeasurable
        ih.1.aestronglyMeasurable, hf1 j, ih.2, mul_one]


/-- `S` is a stopping set for the independent family `G`: the event that the set of
revealed coordinates is exactly `A` is decided by the coordinates in `A`. -/
def IsIndepStoppingSet {Ω ι : Type*} (G : ι → MeasurableSpace Ω) (S : Ω → Finset ι) : Prop :=
  ∀ A : Finset ι, MeasurableSet[indepAlg G (A : Set ι)] {ω | S ω = A}

/-- `E` is decided by the exploration `S`: on the event that the revealed set is `A`,
membership in `E` is decided by the coordinates in `A`. -/
def IndepBlockDecides {Ω ι : Type*} (G : ι → MeasurableSpace Ω) (S : Ω → Finset ι)
    (E : Set Ω) : Prop :=
  ∀ A : Finset ι, MeasurableSet[indepAlg G (A : Set ι)] (E ∩ {ω | S ω = A})


omit mΩ in
/-- The event that a coordinate `i` is not revealed by the stopping set `S` is measurable for
the joint algebra of every other coordinate. -/
theorem measurableSet_notMem_stoppingSet [Fintype ι] {G : ι → MeasurableSpace Ω}
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S) (i : ι) :
    MeasurableSet[indepAlg G ({i}ᶜ : Set ι)] {ω | i ∉ S ω} := by
  classical
  have hset : {ω | i ∉ S ω} = ⋃ A : {A : Finset ι // i ∉ A}, {ω | S ω = (A : Finset ι)} := by
    ext ω
    simp only [Set.mem_iUnion, Set.mem_setOf_eq]
    exact ⟨fun h => ⟨⟨S ω, h⟩, rfl⟩, by rintro ⟨⟨A, hA⟩, rfl⟩; exact hA⟩
  rw [hset]
  refine MeasurableSet.iUnion fun A => ?_
  refine indepAlg_mono G ?_ _ (hS (A : Finset ι))
  intro x hx
  simp only [Set.mem_compl_iff, Set.mem_singleton_iff]
  rintro rfl
  exact A.2 hx

/-- The event that a coordinate `i` is revealed by the stopping set `S` is measurable in the
ambient `σ`-algebra, as the complement of `measurableSet_notMem_stoppingSet`. -/
theorem measurableSet_mem_stoppingSet [Fintype ι] {G : ι → MeasurableSpace Ω}
    (hGle : ∀ i, G i ≤ mΩ) {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S) (i : ι) :
    MeasurableSet {ω | i ∈ S ω} := by
  have h := indepAlg_le hGle ({i}ᶜ : Set ι) _ (measurableSet_notMem_stoppingSet hS i)
  have hc : {ω | i ∈ S ω} = {ω | i ∉ S ω}ᶜ := by ext ω; simp
  rw [hc]
  exact h.compl

/-- Restricted to the event that a fixed coordinate `i` is revealed, the coordinate `ξ i` still
has mean zero, since the indicator of `i ∉ S` is independent of `ξ i`. -/
theorem integral_ite_mem_stoppingSet_eq_zero [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξm : ∀ i, Measurable[G i] (ξ i)) (hξi : ∀ i, Integrable (ξ i) P)
    (hξ0 : ∀ i, ∫ ω, ξ i ω ∂P = 0) (i : ι) :
    ∫ ω, (if i ∈ S ω then ξ i ω else 0) ∂P = 0 := by
  classical
  have hmemset : MeasurableSet {ω | i ∈ S ω} := measurableSet_mem_stoppingSet hGle hS i
  set u : Ω → ℝ := fun ω => if i ∈ S ω then (0 : ℝ) else 1 with hu
  have hueq : u = Set.indicator {ω | i ∉ S ω} (fun _ => (1 : ℝ)) := by
    funext ω
    by_cases h : i ∈ S ω <;> simp [hu, h]
  have humeas : Measurable[indepAlg G ({i}ᶜ : Set ι)] u := by
    rw [hueq]
    exact measurable_const.indicator (measurableSet_notMem_stoppingSet hS i)
  have huint : Integrable u P := by
    rw [hueq]
    exact (integrable_const (1 : ℝ)).indicator
      (indepAlg_le hGle _ _ (measurableSet_notMem_stoppingSet hS i))
  have hξmeas : Measurable[indepAlg G ({i} : Set ι)] (ξ i) :=
    (hξm i).mono (le_indepAlg G (Set.mem_singleton i)) le_rfl
  have hind : IndepFun u (ξ i) P :=
    indepFun_of_indep (indep_indepAlg hGle hGindep (disjoint_compl_left)) humeas hξmeas
  have hmul : ∫ ω, u ω * ξ i ω ∂P = 0 := by
    rw [hind.integral_fun_mul_eq_mul_integral huint.aestronglyMeasurable
      (hξi i).aestronglyMeasurable, hξ0 i, mul_zero]
  have hint1 : Integrable (fun ω => if i ∈ S ω then ξ i ω else 0) P := by
    have : (fun ω => if i ∈ S ω then ξ i ω else 0) = Set.indicator {ω | i ∈ S ω} (ξ i) := by
      funext ω
      by_cases h : i ∈ S ω <;> simp [h]
    rw [this]
    exact (hξi i).indicator hmemset
  have hint2 : Integrable (fun ω => u ω * ξ i ω) P := hind.integrable_mul huint (hξi i)
  have hsplit : ∀ ω, ξ i ω = (if i ∈ S ω then ξ i ω else 0) + u ω * ξ i ω := by
    intro ω
    by_cases h : i ∈ S ω <;> simp [hu, h]
  have hz : ∫ ω, ((if i ∈ S ω then ξ i ω else 0) + u ω * ξ i ω) ∂P = 0 := by
    simp_rw [← hsplit]
    exact hξ0 i
  rw [integral_add hint1 hint2, hmul, add_zero] at hz
  exact hz

/-- The martingale property of the exploration: the sum `∑ i ∈ S ω, ξ i ω` of the revealed
coordinates has mean zero, summing `integral_ite_mem_stoppingSet_eq_zero` over all `i`. -/
theorem integral_sum_stoppingSet_eq_zero [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξm : ∀ i, Measurable[G i] (ξ i)) (hξi : ∀ i, Integrable (ξ i) P)
    (hξ0 : ∀ i, ∫ ω, ξ i ω ∂P = 0) :
    ∫ ω, (∑ i ∈ S ω, ξ i ω) ∂P = 0 := by
  classical
  have hpt : ∀ ω, (∑ i ∈ S ω, ξ i ω)
      = ∑ i ∈ (Finset.univ : Finset ι), (if i ∈ S ω then ξ i ω else 0) := by
    intro ω
    rw [Finset.sum_ite_mem, Finset.univ_inter]
  have hint : ∀ i ∈ (Finset.univ : Finset ι),
      Integrable (fun ω => if i ∈ S ω then ξ i ω else 0) P := by
    intro i _
    have hmemset : MeasurableSet {ω | i ∈ S ω} := measurableSet_mem_stoppingSet hGle hS i
    have : (fun ω => if i ∈ S ω then ξ i ω else 0) = Set.indicator {ω | i ∈ S ω} (ξ i) := by
      funext ω
      by_cases h : i ∈ S ω <;> simp [h]
    rw [this]
    exact (hξi i).indicator hmemset
  simp_rw [hpt]
  rw [integral_finsetSum _ hint]
  refine Finset.sum_eq_zero fun i _ => ?_
  exact integral_ite_mem_stoppingSet_eq_zero hGle hGindep hS ξ hξm hξi hξ0 i

omit mΩ in
/-- Summing the indicator of `E ∩ {S = A}` weighted by `g A` over every possible value `A` of
the stopping set recovers the indicator of `E` weighted by `g` at the actual value `S ω`. -/
theorem indicator_partition_sum [Fintype ι] [DecidableEq ι] (S : Ω → Finset ι) (E : Set Ω)
    (g : Finset ι → Ω → ℝ) (ω : Ω) :
    (∑ A : Finset ι, Set.indicator (E ∩ {ω | S ω = A}) (g A) ω)
      = Set.indicator E (g (S ω)) ω := by
  classical
  rw [Finset.sum_eq_single (S ω)]
  · by_cases h : ω ∈ E <;> simp [h]
  · intro A _ hA
    have hnot : ω ∉ E ∩ {ω | S ω = A} := by
      rintro ⟨-, h2⟩
      exact hA (Set.mem_setOf_eq ▸ h2).symm
    simp [hnot]
  · intro h
    exact absurd (Finset.mem_univ (S ω)) h

/-- On an event `T` decided by the coordinates in `A`, integrating the indicator of `T` against
the full product `∏ i : ι, f i` gives the same value as against the partial product `∏ i ∈ A,
f i`, since the remaining factors are independent of `T` and of mean one. -/
theorem integral_indicator_prod_univ_eq [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    (f : ι → Ω → ℝ) (hfm : ∀ i, Measurable[G i] (f i)) (hfi : ∀ i, Integrable (f i) P)
    (hf1 : ∀ i, ∫ ω, f i ω ∂P = 1) (A : Finset ι) {T : Set Ω}
    (hT : MeasurableSet[indepAlg G (A : Set ι)] T) :
    ∫ ω, Set.indicator T (fun ω => ∏ i : ι, f i ω) ω ∂P
      = ∫ ω, Set.indicator T (fun ω => ∏ i ∈ A, f i ω) ω ∂P := by
  classical
  have hTm : MeasurableSet T := indepAlg_le hGle _ _ hT
  have hXm : Measurable[indepAlg G (A : Set ι)]
      (Set.indicator T (fun ω => ∏ i ∈ A, f i ω)) :=
    (measurable_finset_prod f hfm A).indicator hT
  have hYm : Measurable[indepAlg G ((Aᶜ : Finset ι) : Set ι)] (fun ω => ∏ i ∈ Aᶜ, f i ω) :=
    measurable_finset_prod f hfm Aᶜ
  have hdisj : Disjoint ((A : Set ι)) (((Aᶜ : Finset ι) : Set ι)) := by
    rw [Finset.coe_compl]
    exact disjoint_compl_right
  have hind : IndepFun (Set.indicator T (fun ω => ∏ i ∈ A, f i ω))
      (fun ω => ∏ i ∈ Aᶜ, f i ω) P :=
    indepFun_of_indep (indep_indepAlg hGle hGindep hdisj) hXm hYm
  have hApair := integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1 A
  have hAcpair := integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1 Aᶜ
  have hXint : Integrable (Set.indicator T (fun ω => ∏ i ∈ A, f i ω)) P :=
    hApair.1.indicator hTm
  have hptwise : ∀ ω, Set.indicator T (fun ω => ∏ i : ι, f i ω) ω
      = Set.indicator T (fun ω => ∏ i ∈ A, f i ω) ω * (∏ i ∈ Aᶜ, f i ω) := by
    intro ω
    by_cases h : ω ∈ T
    · rw [Set.indicator_of_mem h, Set.indicator_of_mem h, Finset.prod_mul_prod_compl]
    · rw [Set.indicator_of_notMem h, Set.indicator_of_notMem h, zero_mul]
  simp_rw [hptwise]
  rw [hind.integral_fun_mul_eq_mul_integral hXint.aestronglyMeasurable
    hAcpair.1.aestronglyMeasurable, hAcpair.2, mul_one]

/-- The adaptive Cameron--Martin identity: on an event decided by the exploration, the
density that tilts only the revealed coordinates gives the same integral as the density
that tilts every coordinate. -/
theorem integral_indicator_stoppedDensity_eq [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (f : ι → Ω → ℝ) (hfm : ∀ i, Measurable[G i] (f i))
    (hfi : ∀ i, Integrable (f i) P) (hf1 : ∀ i, ∫ ω, f i ω ∂P = 1)
    {E : Set Ω} (hE : IndepBlockDecides G S E) :
    ∫ ω, Set.indicator E (fun ω => ∏ i ∈ S ω, f i ω) ω ∂P
      = ∫ ω, Set.indicator E (fun ω => ∏ i : ι, f i ω) ω ∂P := by
  classical
  have hTm : ∀ A : Finset ι, MeasurableSet (E ∩ {ω | S ω = A}) :=
    fun A => indepAlg_le hGle _ _ (hE A)
  have hstep : ∀ A : Finset ι,
      Integrable (Set.indicator (E ∩ {ω | S ω = A}) (fun ω => ∏ i ∈ A, f i ω)) P :=
    fun A => (integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1 A).1.indicator (hTm A)
  have hstep' : ∀ A : Finset ι,
      Integrable (Set.indicator (E ∩ {ω | S ω = A}) (fun ω => ∏ i : ι, f i ω)) P :=
    fun A => (integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1
      Finset.univ).1.indicator (hTm A)
  have hL : ∫ ω, Set.indicator E (fun ω => ∏ i ∈ S ω, f i ω) ω ∂P
      = ∑ A : Finset ι, ∫ ω,
          Set.indicator (E ∩ {ω | S ω = A}) (fun ω => ∏ i ∈ A, f i ω) ω ∂P := by
    rw [← integral_finsetSum _ (fun A _ => hstep A)]
    refine integral_congr_ae ?_
    filter_upwards with ω
    exact (indicator_partition_sum S E (fun A ω => ∏ i ∈ A, f i ω) ω).symm
  have hR : ∫ ω, Set.indicator E (fun ω => ∏ i : ι, f i ω) ω ∂P
      = ∑ A : Finset ι, ∫ ω,
          Set.indicator (E ∩ {ω | S ω = A}) (fun ω => ∏ i : ι, f i ω) ω ∂P := by
    rw [← integral_finsetSum _ (fun A _ => hstep' A)]
    refine integral_congr_ae ?_
    filter_upwards with ω
    exact (indicator_partition_sum S E (fun _ ω => ∏ i : ι, f i ω) ω).symm
  rw [hL, hR]
  refine Finset.sum_congr rfl fun A _ => ?_
  exact (integral_indicator_prod_univ_eq hGle hGindep f hfm hfi hf1 A (hE A)).symm

/-- The stopped product `∏ i ∈ S ω, f i ω` of the density factors over the revealed set is
integrable, summing `integrable_finset_prod_and_integral` over every possible value of `S`. -/
theorem integrable_stoppedDensity [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (f : ι → Ω → ℝ) (hfm : ∀ i, Measurable[G i] (f i)) (hfi : ∀ i, Integrable (f i) P)
    (hf1 : ∀ i, ∫ ω, f i ω ∂P = 1) :
    Integrable (fun ω => ∏ i ∈ S ω, f i ω) P := by
  classical
  have hTm : ∀ A : Finset ι, MeasurableSet {ω | S ω = A} :=
    fun A => indepAlg_le hGle _ _ (hS A)
  have hsum : Integrable (fun ω => ∑ A : Finset ι,
      Set.indicator {ω | S ω = A} (fun ω => ∏ i ∈ A, f i ω) ω) P :=
    integrable_finsetSum _ fun A _ =>
      (integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1 A).1.indicator (hTm A)
  refine hsum.congr ?_
  filter_upwards with ω
  have h := indicator_partition_sum S Set.univ (fun A ω => ∏ i ∈ A, f i ω) ω
  simpa [Set.univ_inter] using h

/-- The stopped density `∏ i ∈ S ω, f i ω` integrates to one, specializing
`integral_indicator_stoppedDensity_eq` to `E = Set.univ`. -/
theorem integral_stoppedDensity_eq_one [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (f : ι → Ω → ℝ) (hfm : ∀ i, Measurable[G i] (f i)) (hfi : ∀ i, Integrable (f i) P)
    (hf1 : ∀ i, ∫ ω, f i ω ∂P = 1) :
    ∫ ω, (∏ i ∈ S ω, f i ω) ∂P = 1 := by
  classical
  have huniv : IndepBlockDecides G S Set.univ := by
    intro A
    simpa [Set.univ_inter] using hS A
  have h := integral_indicator_stoppedDensity_eq hGle hGindep f hfm hfi hf1 huniv
  simp only [Set.indicator_univ] at h
  rw [h]
  exact (integrable_finset_prod_and_integral hGle hGindep f hfm hfi hf1 Finset.univ).2

/-- The relative entropy of a probability measure with respect to an exponential tilt of
itself by a normalized density is minus the mean of the log-density. -/
theorem klDiv_tilted_self [IsProbabilityMeasure P] (F : Ω → ℝ) (hFint : Integrable F P)
    (hexpint : Integrable (fun ω => Real.exp (F ω)) P)
    (hexp1 : ∫ ω, Real.exp (F ω) ∂P = 1) :
    InformationTheory.klDiv P (P.tilted F) = ENNReal.ofReal (-(∫ ω, F ω ∂P)) := by
  haveI : IsProbabilityMeasure (P.tilted F) := isProbabilityMeasure_tilted hexpint
  have hrefl : P ≪ P := Measure.AbsolutelyContinuous.refl P
  have hac : P ≪ P.tilted F := absolutelyContinuous_tilted hexpint
  have hllrself : Integrable (llr P P) P := by
    rw [integrable_congr (llr_self P)]
    exact integrable_zero _ _ _
  have hllrzero : ∫ ω, llr P P ω ∂P = 0 := by
    rw [integral_congr_ae (llr_self P)]
    simp
  have hintllr : Integrable (llr P (P.tilted F)) P :=
    integrable_llr_tilted_right hrefl hFint hllrself hexpint
  have hval : ∫ ω, llr P (P.tilted F) ω ∂P = -(∫ ω, F ω ∂P) := by
    rw [integral_llr_tilted_right hrefl hFint hexpint hllrself, hexp1, Real.log_one, hllrzero]
    ring
  rw [InformationTheory.klDiv_of_ac_of_integrable hac hintllr, hval]
  simp

/-- The Cameron--Martin factor of a shift of size `a` in the direction of the `i`-th
coordinate: the density of the shifted standard Gaussian coordinate. -/
noncomputable def cmFactor {Ω ι : Type*} (a : ℝ) (ξ : ι → Ω → ℝ) (i : ι) (ω : Ω) : ℝ :=
  Real.exp (a * ξ i ω - a ^ 2 / 2)

/-- The logarithm of the adaptive Cameron--Martin density: the shift is applied only to the
coordinates the exploration reveals. -/
noncomputable def cmLogDensity {Ω ι : Type*} (a : ℝ) (ξ : ι → Ω → ℝ) (S : Ω → Finset ι)
    (ω : Ω) : ℝ :=
  a * (∑ i ∈ S ω, ξ i ω) - a ^ 2 / 2 * ((S ω).card : ℝ)

omit mΩ in
/-- The exponential of the adaptive log-density `cmLogDensity` factors into a product of the
per-coordinate Cameron–Martin factors `cmFactor` over the revealed coordinates. -/
theorem exp_cmLogDensity (a : ℝ) (ξ : ι → Ω → ℝ) (S : Ω → Finset ι) (ω : Ω) :
    Real.exp (cmLogDensity a ξ S ω) = ∏ i ∈ S ω, cmFactor a ξ i ω := by
  simp only [cmFactor, cmLogDensity]
  rw [← Real.exp_sum]
  congr 1
  rw [Finset.sum_sub_distrib, ← Finset.mul_sum, Finset.sum_const, nsmul_eq_mul]
  ring

omit mΩ in
/-- Each Cameron–Martin factor `cmFactor a ξ i` is measurable for the coordinate algebra
`G i`, being built from the measurable coordinate `ξ i` by an affine map composed with `exp`. -/
theorem measurable_cmFactor {G : ι → MeasurableSpace Ω} (a : ℝ) (ξ : ι → Ω → ℝ)
    (hξm : ∀ i, Measurable[G i] (ξ i)) (i : ι) : Measurable[G i] (cmFactor a ξ i) :=
  (((hξm i).const_mul a).sub_const (a ^ 2 / 2)).exp

omit mΩ in
/-- The number of revealed coordinates, as a sum of indicators. -/
theorem card_stoppingSet_eq_sum [Fintype ι] [DecidableEq ι] (S : Ω → Finset ι) (ω : Ω) :
    ((S ω).card : ℝ) = ∑ i : ι, (if i ∈ S ω then (1 : ℝ) else 0) := by
  rw [Finset.sum_ite_mem, Finset.univ_inter, Finset.sum_const, nsmul_eq_mul, mul_one]

/-- The number of revealed coordinates `(S ω).card` is integrable, being a finite sum of
indicators of the measurable events `measurableSet_mem_stoppingSet`. -/
theorem integrable_card_stoppingSet [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S) :
    Integrable (fun ω => ((S ω).card : ℝ)) P := by
  classical
  have hsum : Integrable (fun ω => ∑ i : ι, (if i ∈ S ω then (1 : ℝ) else 0)) P := by
    refine integrable_finsetSum _ fun i _ => ?_
    have hmemset : MeasurableSet {ω | i ∈ S ω} := measurableSet_mem_stoppingSet hGle hS i
    have heq : (fun ω => if i ∈ S ω then (1 : ℝ) else 0)
        = Set.indicator {ω | i ∈ S ω} (fun _ => (1 : ℝ)) := by
      funext ω
      by_cases h : i ∈ S ω <;> simp [h]
    rw [heq]
    exact (integrable_const (1 : ℝ)).indicator hmemset
  refine hsum.congr ?_
  filter_upwards with ω
  exact (card_stoppingSet_eq_sum S ω).symm

/-- The sum `∑ i ∈ S ω, ξ i ω` over the revealed coordinates is integrable, being a finite sum
of the integrable coordinates `ξ i` restricted to the measurable event `i ∈ S`. -/
theorem integrable_sum_stoppingSet [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξi : ∀ i, Integrable (ξ i) P) :
    Integrable (fun ω => ∑ i ∈ S ω, ξ i ω) P := by
  classical
  have hsum : Integrable (fun ω => ∑ i : ι, (if i ∈ S ω then ξ i ω else 0)) P := by
    refine integrable_finsetSum _ fun i _ => ?_
    have hmemset : MeasurableSet {ω | i ∈ S ω} := measurableSet_mem_stoppingSet hGle hS i
    have heq : (fun ω => if i ∈ S ω then ξ i ω else 0) = Set.indicator {ω | i ∈ S ω} (ξ i) := by
      funext ω
      by_cases h : i ∈ S ω <;> simp [h]
    rw [heq]
    exact (hξi i).indicator hmemset
  refine hsum.congr ?_
  filter_upwards with ω
  rw [Finset.sum_ite_mem, Finset.univ_inter]

omit mΩ in
/-- The constant exploration that reveals every coordinate is trivially a stopping set for any
family `G`. -/
theorem isIndepStoppingSet_univ [Fintype ι] (G : ι → MeasurableSpace Ω) :
    IsIndepStoppingSet G (fun _ : Ω => (Finset.univ : Finset ι)) := by
  intro A
  by_cases h : (Finset.univ : Finset ι) = A
  · simp [h]
  · simp [h]

omit mΩ in
/-- An event `E` decided by the exploration `S` is measurable in any ambient algebra `mΩ'` each
`G i` sits below, covering `E` by its intersections with the finitely many events `S = A`. -/
theorem measurableSet_of_indepBlockDecides [Fintype ι] {G : ι → MeasurableSpace Ω}
    {mΩ' : MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ') {S : Ω → Finset ι} {E : Set Ω}
    (hE : IndepBlockDecides G S E) : MeasurableSet[mΩ'] E := by
  classical
  have hcover : E = ⋃ A : Finset ι, (E ∩ {ω | S ω = A}) := by
    ext ω
    simp only [Set.mem_iUnion, Set.mem_inter_iff, Set.mem_setOf_eq]
    exact ⟨fun h => ⟨S ω, h, rfl⟩, fun ⟨_, h, _⟩ => h⟩
  rw [hcover]
  exact MeasurableSet.iUnion fun A => indepAlg_le hGle _ _ (hE A)

/-- The relative entropy of the adaptive Cameron--Martin tilt is `a²/2` times the expected
number of revealed coordinates. -/
theorem klDiv_tilted_cm_le [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξm : ∀ i, Measurable[G i] (ξ i)) (hξi : ∀ i, Integrable (ξ i) P)
    (hξ0 : ∀ i, ∫ ω, ξ i ω ∂P = 0) (a : ℝ)
    (hfi : ∀ i, Integrable (cmFactor a ξ i) P)
    (hf1 : ∀ i, ∫ ω, cmFactor a ξ i ω ∂P = 1)
    (N : ℝ) (hN : ∫ ω, ((S ω).card : ℝ) ∂P ≤ N) :
    InformationTheory.klDiv P (P.tilted (cmLogDensity a ξ S))
      ≤ ENNReal.ofReal (a ^ 2 / 2 * N) := by
  classical
  have hfm : ∀ i, Measurable[G i] (cmFactor a ξ i) := measurable_cmFactor a ξ hξm
  have hMint : Integrable (fun ω => ∑ i ∈ S ω, ξ i ω) P :=
    integrable_sum_stoppingSet hGle hS ξ hξi
  have hKint : Integrable (fun ω => ((S ω).card : ℝ)) P := integrable_card_stoppingSet hGle hS
  have hFint : Integrable (cmLogDensity a ξ S) P := by
    refine ((hMint.const_mul a).sub (hKint.const_mul (a ^ 2 / 2))).congr ?_
    filter_upwards with ω
    simp [cmLogDensity]
  have hexpint : Integrable (fun ω => Real.exp (cmLogDensity a ξ S ω)) P := by
    simp_rw [exp_cmLogDensity]
    exact integrable_stoppedDensity hGle hGindep hS (cmFactor a ξ) hfm hfi hf1
  have hexp1 : ∫ ω, Real.exp (cmLogDensity a ξ S ω) ∂P = 1 := by
    simp_rw [exp_cmLogDensity]
    exact integral_stoppedDensity_eq_one hGle hGindep hS (cmFactor a ξ) hfm hfi hf1
  have hM0 : ∫ ω, (∑ i ∈ S ω, ξ i ω) ∂P = 0 :=
    integral_sum_stoppingSet_eq_zero hGle hGindep hS ξ hξm hξi hξ0
  have hFval : ∫ ω, cmLogDensity a ξ S ω ∂P
      = -(a ^ 2 / 2 * ∫ ω, ((S ω).card : ℝ) ∂P) := by
    simp only [cmLogDensity]
    rw [integral_sub ((hMint.const_mul a)) (hKint.const_mul (a ^ 2 / 2)),
      integral_const_mul, integral_const_mul, hM0, mul_zero, zero_sub]
  rw [klDiv_tilted_self (cmLogDensity a ξ S) hFint hexpint hexp1, hFval, neg_neg]
  refine ENNReal.ofReal_le_ofReal ?_
  have ha : (0 : ℝ) ≤ a ^ 2 / 2 := by positivity
  exact mul_le_mul_of_nonneg_left hN ha

omit mΩ in
/-- If the exploration `S` decides `E`, then so does the trivial exploration that always
reveals every coordinate, since `E` is already measurable for the full joint algebra. -/
theorem indepBlockDecides_univ [Fintype ι] {G : ι → MeasurableSpace Ω} {S : Ω → Finset ι}
    {E : Set Ω} (hE : IndepBlockDecides G S E) :
    IndepBlockDecides G (fun _ : Ω => (Finset.univ : Finset ι)) E := by
  classical
  have hEu : MeasurableSet[indepAlg G (Set.univ : Set ι)] E :=
    measurableSet_of_indepBlockDecides (fun i => le_indepAlg G (Set.mem_univ i)) hE
  intro A
  by_cases h : (Finset.univ : Finset ι) = A
  · have hA : ((A : Finset ι) : Set ι) = (Set.univ : Set ι) := by
      rw [← h, Finset.coe_univ]
    rw [hA]
    simpa [h] using hEu
  · simp [h]

/-- The adaptive tilt and the full tilt agree on every event the exploration decides. -/
theorem tilted_cm_apply_eq_of_decided [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξm : ∀ i, Measurable[G i] (ξ i)) (a : ℝ)
    (hfi : ∀ i, Integrable (cmFactor a ξ i) P)
    (hf1 : ∀ i, ∫ ω, cmFactor a ξ i ω ∂P = 1)
    {E : Set Ω} (hE : IndepBlockDecides G S E) :
    (P.tilted (cmLogDensity a ξ S)) E
      = (P.tilted (cmLogDensity a ξ (fun _ : Ω => (Finset.univ : Finset ι)))) E := by
  classical
  have hfm : ∀ i, Measurable[G i] (cmFactor a ξ i) := measurable_cmFactor a ξ hξm
  have hEmeas : MeasurableSet E := measurableSet_of_indepBlockDecides hGle hE
  have hexp1S : ∫ ω, Real.exp (cmLogDensity a ξ S ω) ∂P = 1 := by
    simp_rw [exp_cmLogDensity]
    exact integral_stoppedDensity_eq_one hGle hGindep hS (cmFactor a ξ) hfm hfi hf1
  have hexp1U : ∫ ω, Real.exp (cmLogDensity a ξ (fun _ : Ω => (Finset.univ : Finset ι)) ω) ∂P
      = 1 := by
    simp_rw [exp_cmLogDensity]
    exact integral_stoppedDensity_eq_one hGle hGindep (isIndepStoppingSet_univ G)
      (cmFactor a ξ) hfm hfi hf1
  rw [tilted_apply_eq_ofReal_integral _ E, tilted_apply_eq_ofReal_integral _ E, hexp1S, hexp1U]
  simp only [div_one]
  congr 1
  rw [← integral_indicator hEmeas, ← integral_indicator hEmeas]
  simp_rw [exp_cmLogDensity]
  exact integral_indicator_stoppedDensity_eq hGle hGindep (cmFactor a ξ) hfm hfi hf1 hE

/-- The exponential of the adaptive log-density is integrable, since by `exp_cmLogDensity` it
equals the integrable stopped product of Cameron–Martin factors. -/
theorem integrable_exp_cmLogDensity [Fintype ι] [DecidableEq ι] [IsProbabilityMeasure P]
    {G : ι → MeasurableSpace Ω} (hGle : ∀ i, G i ≤ mΩ) (hGindep : iIndep G P)
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet G S)
    (ξ : ι → Ω → ℝ) (hξm : ∀ i, Measurable[G i] (ξ i)) (a : ℝ)
    (hfi : ∀ i, Integrable (cmFactor a ξ i) P)
    (hf1 : ∀ i, ∫ ω, cmFactor a ξ i ω ∂P = 1) :
    Integrable (fun ω => Real.exp (cmLogDensity a ξ S ω)) P := by
  simp_rw [exp_cmLogDensity]
  exact integrable_stoppedDensity hGle hGindep hS (cmFactor a ξ)
    (measurable_cmFactor a ξ hξm) hfi hf1

end Sandpile.Support
