import Sandpile.Support.CrossPath

/-!
# Vacuity of continuum crossing events off continuous sample paths

The crossing events of `sandpile.tex:2112-2118` are events about a field
indexed by the plane, and the plane is uncountable.  On the space of ALL
functions `ℝ² → ℝ` the product σ-algebra is generated by the evaluations, so
every set measurable for it is determined by the values at countably many
points.  A rectangle crossing event is not: a function can be made to cross a
nondegenerate rectangle while its values at any prescribed countable set of
points are arbitrary, by putting the level on one horizontal segment that
misses that countable set.

The consequence, proved below, is that for EVERY probability measure `μ` on
`Space 2 → ℝ` and every rectangle with `a 0 ≤ b 0` and `a 1 < b 1`,
`μ (crossingEvent a b level) = 1`, the outer measure of the crossing event
being computed over measurable supersets, of which the whole space is the only
one.  A statement that compares crossing probabilities of such a law therefore
compares the number one with itself.

The continuum RSW comparison was such a statement until it was restated on the
field; the statement it had is copied below as
`oldContinuumRSW`, and `oldContinuumRSW_holds` proves it outright, with the
identity comparison map.  It carries no information about crossings, and neither does any
hypothesis of the form `c ≤ μ (crossingEvent …)` or
`μ (crossingEvent …) ≤ …`.  This is a defect of the transcription, not of the
paper: the Köhler-Schindler and Tassion comparison is a statement about a
random continuous field, and the crossing events of a random CONTINUOUS field
are perfectly good events, since a continuous function is determined by its
values on a countable dense set.  The repair is to carry the continuity of the
sample paths into the statement, either by taking the law on the space of
continuous functions or by keeping the field on its probability space, where
the crossing event is sandwiched between the countably determined events of
`sandpile.tex:2112-2118` read along a countable dense set.

Nothing in this file is used to discharge any node of the paper.  It is the
record of why the continuum crossing vocabulary of
`Sandpile/Support/ContinuumPlanar.lean` had to be restated before
`prop:fixed-scale-crossings` could be proved from it; the vocabulary that
replaced it is the field form of `Sandpile/Support/CrossField.lean`, in which
the crossing probability is the outer measure of a subset of the probability
space carrying the field.
-/

open MeasureTheory Set

namespace Sandpile.Support

open Sandpile.Continuum Sandpile.Frozen.FixedScaleCrossings

/-- A set of functions `ι → α` is countably determined when membership in it
depends only on the values at countably many indices. -/
def CountablyDetermined {ι α : Type*} (F : Set (ι → α)) : Prop :=
  ∃ S : Set ι, S.Countable ∧ ∀ x y : ι → α, (∀ i ∈ S, x i = y i) → (x ∈ F ↔ y ∈ F)

/-- The countably determined sets form a σ-algebra. -/
@[reducible]
def countablyDeterminedSpace (ι α : Type*) : MeasurableSpace (ι → α) where
  MeasurableSet' := CountablyDetermined
  measurableSet_empty := ⟨∅, countable_empty, fun _ _ _ => Iff.rfl⟩
  measurableSet_compl := by
    rintro F ⟨S, hS, hF⟩
    exact ⟨S, hS, fun x y hxy => not_congr (hF x y hxy)⟩
  measurableSet_iUnion := by
    intro f hf
    choose S hS hSF using hf
    refine ⟨⋃ n, S n, countable_iUnion hS, fun x y hxy => ?_⟩
    simp only [Set.mem_iUnion]
    constructor
    · rintro ⟨n, hn⟩
      exact ⟨n, (hSF n x y (fun i hi => hxy i (Set.mem_iUnion.2 ⟨n, hi⟩))).1 hn⟩
    · rintro ⟨n, hn⟩
      exact ⟨n, (hSF n x y (fun i hi => hxy i (Set.mem_iUnion.2 ⟨n, hi⟩))).2 hn⟩

/-- The product σ-algebra is generated by the evaluations, so every set
measurable for it is determined by countably many coordinates. -/
theorem countablyDetermined_of_measurableSet {ι α : Type*} [MeasurableSpace α]
    {F : Set (ι → α)} (hF : MeasurableSet F) : CountablyDetermined F := by
  have hle : (MeasurableSpace.pi : MeasurableSpace (ι → α)) ≤ countablyDeterminedSpace ι α := by
    refine iSup_le fun i => ?_
    rintro s ⟨t, _, rfl⟩
    exact ⟨{i}, countable_singleton i, fun x y hxy => by
      simp only [Set.mem_preimage]
      rw [hxy i rfl]⟩
  exact hle F hF

/-- A countable set of plane points misses all but countably many heights, and
a nondegenerate interval of heights is uncountable. -/
theorem exists_height_notMem {S : Set (Sandpile.Continuum.Space 2)} (hS : S.Countable)
    {lo hi : ℝ} (h : lo < hi) :
    ∃ c, lo < c ∧ c < hi ∧ ∀ p ∈ S, p 1 ≠ c := by
  by_contra hcon
  push Not at hcon
  have hsub : Set.Ioo lo hi ⊆ (fun p : Sandpile.Continuum.Space 2 => p 1) '' S := by
    intro c hc
    obtain ⟨p, hp, hpc⟩ := hcon c hc.1 hc.2
    exact ⟨p, hp, hpc⟩
  have hcount : (Set.Ioo lo hi).Countable := Set.Countable.mono hsub (hS.image _)
  exact absurd (Cardinal.Real.Ioo_countable_iff.mp hcount) (not_le.mpr h)

/-- The crossing event of a nondegenerate rectangle has outer measure one for
every probability measure on the space of all planar functions.  The only
measurable superset of the event is the whole space: a measurable set is
determined by countably many points, some horizontal line misses all of them,
and putting the level on that line makes any prescribed function cross. -/
theorem measure_crossingEvent_eq_one (μ : Measure (Sandpile.Continuum.Space 2 → ℝ))
    [IsProbabilityMeasure μ] (a b : Fin 2 → ℝ) (h0 : a 0 ≤ b 0) (h1 : a 1 < b 1) (level : ℝ) :
    μ (Sandpile.Continuum.crossingEvent a b level) = 1 := by
  classical
  set E := Sandpile.Continuum.crossingEvent a b level with hE
  obtain ⟨S, hS, hdet⟩ :=
    countablyDetermined_of_measurableSet (measurableSet_toMeasurable μ E)
  obtain ⟨c, hc0, hc1, hcS⟩ := exists_height_notMem hS h1
  have huniv : toMeasurable μ E = Set.univ := by
    refine Set.eq_univ_of_forall fun g => ?_
    have hXcross : (fun p : Sandpile.Continuum.Space 2 => if p ∈ S then g p else level) ∈ E := by
      refine crosses_hSeg h0 hc0.le hc1.le fun t _ _ => ?_
      have hnot : hSeg c t ∉ S := fun hmem => hcS _ hmem (hSeg_apply_one c t)
      simp [hnot]
    exact (hdet _ g (fun i hi => by simp [hi])).1 (subset_toMeasurable μ E hXcross)
  rw [← measure_toMeasurable E, huniv, measure_univ]

/-- The continuum crossing comparison as it was stated before that
restatement: a comparison of the crossing probabilities of a law on the space
of ALL planar functions.  Kept here, and nowhere else, as the statement the
record below is about. -/
def oldContinuumRSW : Prop :=
  ∀ ρ : ℝ, 1 ≤ ρ → ∃ ψ : Set.Icc (0 : ℝ) 1 ≃o Set.Icc (0 : ℝ) 1,
    ∀ μ : Measure (Sandpile.Continuum.Space 2 → ℝ), ∀ [IsProbabilityMeasure μ],
      Sandpile.Continuum.IsSymmetricContinuumLaw μ →
        Sandpile.Continuum.IsAssociatedContinuumLaw μ →
      ∀ R : ℝ, 1 ≤ R → ∀ level : ℝ,
        (ψ (Sandpile.probabilityInUnitInterval μ
          (Sandpile.Continuum.crossingEvent ![0, 0] ![(2 * R), (2 * ρ * R)] level)) : ℝ) ≤
        μ.real (Sandpile.Continuum.crossingEvent ![0, 0] ![(2 * ρ * R), (2 * R)] level)

/-- The comparison in its old form is a theorem, with the identity comparison
map: both sides of its inequality are the number one, by
`measure_crossingEvent_eq_one`.  That form therefore carried none of the content
of the crossing comparison it was meant to record, which is why the crossing
vocabulary was restated on fields with continuous sample paths. -/
theorem oldContinuumRSW_holds : oldContinuumRSW := by
  intro ρ hρ
  refine ⟨OrderIso.refl _, fun μ _ _ _ R hR level => ?_⟩
  have hone : μ (Sandpile.Continuum.crossingEvent ![0, 0] ![2 * ρ * R, 2 * R] level) = 1 := by
    refine measure_crossingEvent_eq_one μ _ _ ?_ ?_ level
    · simp only [Matrix.cons_val_zero]
      nlinarith
    · simp only [Matrix.cons_val_one, Matrix.cons_val_zero]
      linarith
  have hreal : μ.real (Sandpile.Continuum.crossingEvent ![0, 0] ![2 * ρ * R, 2 * R] level) = 1 := by
    simp [measureReal_def, hone]
  rw [hreal]
  exact (Sandpile.probabilityInUnitInterval μ
    (Sandpile.Continuum.crossingEvent ![0, 0] ![2 * R, 2 * ρ * R] level)).2.2

end Sandpile.Support
