/-
The white noise read block by block, as Step 3 of `prop:fixed-scale-crossings`
(`sandpile.tex:2334-2360`) reads it.

  "``Processing'' this square means revealing the restrictions of `𝒲` to the cubes in
   `𝒜(z)` which have not already been revealed."

A block is a region `Q` of `ℝ^d`; the information it carries is the white noise tested
against every square-integrable function that vanishes off `Q`, and `noiseBlockAlg` is the
sigma-algebra it generates.  Blocks over disjoint regions are independent, because the test
functions they use have pointwise vanishing products and the white noise is a Gaussian family
with the `L²` covariance (`Sandpile.Support.iIndepFun_whiteNoise_of_disjoint`).

This module instantiates the abstract adaptive Cameron--Martin comparison of
`Sandpile/Support/CrossStoppingSet.lean` at these blocks, with the shift carried by the
indicator of each block: the coordinate `𝒲(1_Q)` of a block of volume one is a standard
Gaussian, so the tilt by `exp(a 𝒲(1_Q) - a²/2)` is the Cameron--Martin shift of size `a` in
the direction `1_Q`, which is what the paper's density `(ℓ/𝔪)dz` does on one revealed cube.

What remains for the fixed-scale proposition is the exploration itself: a stopping set for
these blocks whose expected size is `O(R^{2-α₁})`, the fact that the bottom-top crossing event
is decided by the blocks the exploration reveals, and the identification of the fully tilted
measure with the law of the shifted field.
-/
import Sandpile.Support.CrossAdaptiveLoss
import Sandpile.Support.CrossArmIndep
import Sandpile.Support.ContWhiteNoise
import Sandpile.Support.ContCell

open MeasureTheory ProbabilityTheory
open Sandpile.Continuum
open scoped NNReal ENNReal

namespace Sandpile.Support

variable {Ω : Type} [MeasurableSpace Ω] {d : ℕ} {P : Measure Ω}

/-- The square-integrable test functions that vanish off `Q`. -/
abbrev NoiseBlockIndex (d : ℕ) (Q : Set (Space d)) : Type :=
  {g : Space d → ℝ // MemLp g 2 (volume : Measure (Space d)) ∧ ∀ y, y ∉ Q → g y = 0}

/-- All the white-noise values the block `Q` carries. -/
def noiseBlock (W : (Space d → ℝ) → Ω → ℝ) (Q : Set (Space d)) (ω : Ω) :
    NoiseBlockIndex d Q → ℝ :=
  fun g => W (g : Space d → ℝ) ω

/-- The sigma-algebra generated by the white noise on the block `Q`. -/
@[reducible] def noiseBlockAlg (W : (Space d → ℝ) → Ω → ℝ) (Q : Set (Space d)) :
    MeasurableSpace Ω :=
  MeasurableSpace.comap (noiseBlock W Q) inferInstance

theorem measurable_noiseBlock {W : (Space d → ℝ) → Ω → ℝ}
    (hW : IsWhiteNoise d W P) (Q : Set (Space d)) : Measurable (noiseBlock W Q) :=
  measurable_pi_lambda _ fun g => hW.meas _ g.2.1

theorem noiseBlockAlg_le {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P)
    (Q : Set (Space d)) : noiseBlockAlg W Q ≤ ‹MeasurableSpace Ω› :=
  (measurable_noiseBlock hW Q).comap_le

omit [MeasurableSpace Ω] in
/-- Every white-noise value at a test function vanishing off `Q` is read by the block `Q`. -/
theorem measurable_noiseBlockAlg_eval {W : (Space d → ℝ) → Ω → ℝ} {Q : Set (Space d)}
    {g : Space d → ℝ} (hg : MemLp g 2 (volume : Measure (Space d)))
    (hsupp : ∀ y, y ∉ Q → g y = 0) : Measurable[noiseBlockAlg W Q] (W g) := by
  intro s hs
  exact ⟨(fun x : NoiseBlockIndex d Q → ℝ => x ⟨g, hg, hsupp⟩) ⁻¹' s,
    (measurable_pi_apply _) hs, rfl⟩

/-- Blocks over pairwise disjoint regions are independent. -/
theorem iIndep_noiseBlockAlg [IsProbabilityMeasure P] {W : (Space d → ℝ) → Ω → ℝ}
    (hW : IsWhiteNoise d W P) {ι : Type} (Q : ι → Set (Space d))
    (hdisj : ∀ i j, i ≠ j → Disjoint (Q i) (Q j)) :
    iIndep (fun i => noiseBlockAlg W (Q i)) P := by
  have hfun : iIndepFun (fun i => noiseBlock W (Q i)) P := by
    refine iIndepFun_whiteNoise_of_disjoint hW
      (fun (i : ι) (g : NoiseBlockIndex d (Q i)) => (g : Space d → ℝ))
      (fun i g => g.2.1) ?_
    intro i j hij g h y
    by_cases hy : y ∈ Q i
    · have : y ∉ Q j := Set.disjoint_left.mp (hdisj i j hij) hy
      rw [h.2.2 y this, mul_zero]
    · rw [g.2.2 y hy, zero_mul]
  exact hfun.iIndep

/-- The indicator of a block of volume one is a legitimate test function for that block. -/
theorem memLp_blockIndicator {Q : Set (Space d)} (hQm : MeasurableSet Q)
    (hQvol : volume Q = 1) :
    MemLp (Set.indicator Q (fun _ => (1 : ℝ))) 2 (volume : Measure (Space d)) :=
  memLp_indicator_const 2 hQm (1 : ℝ) (Or.inr (by rw [hQvol]; exact ENNReal.one_ne_top))

theorem blockIndicator_self_integral {Q : Set (Space d)} (hQm : MeasurableSet Q)
    (hQvol : volume Q = 1) :
    ∫ y : Space d, Set.indicator Q (fun _ => (1 : ℝ)) y * Set.indicator Q (fun _ => (1 : ℝ)) y
      = 1 := by
  have hpt : ∀ y : Space d,
      Set.indicator Q (fun _ => (1 : ℝ)) y * Set.indicator Q (fun _ => (1 : ℝ)) y
        = Set.indicator Q (fun _ => (1 : ℝ)) y := by
    intro y
    by_cases hy : y ∈ Q <;> simp [hy]
  simp_rw [hpt]
  rw [integral_indicator_const (1 : ℝ) hQm]
  simp [measureReal_def, hQvol]

/-- The block coordinate of a block of volume one is a standard Gaussian. -/
theorem map_blockIndicator_eq_gaussianReal [IsProbabilityMeasure P]
    {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P) {Q : Set (Space d)}
    (hQm : MeasurableSet Q) (hQvol : volume Q = 1) :
    P.map (W (Set.indicator Q (fun _ => (1 : ℝ)))) = gaussianReal 0 1 := by
  rw [map_whiteNoise_eq_gaussianReal W P hW _ (memLp_blockIndicator hQm hQvol),
    blockIndicator_self_integral hQm hQvol]
  norm_num

/-- The coordinate a block of volume one carries is integrable. -/
theorem integrable_blockIndicator [IsProbabilityMeasure P] {W : (Space d → ℝ) → Ω → ℝ}
    (hW : IsWhiteNoise d W P) (Q : Set (Space d)) :
    Integrable (W (Set.indicator Q (fun _ => (1 : ℝ)))) P :=
  (hW.gaussian.hasGaussianLaw_eval _).memLp_two.integrable (by norm_num)

theorem integrable_blockIndicator_cmFactor [IsProbabilityMeasure P]
    {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P) {Q : Set (Space d)}
    (hQm : MeasurableSet Q) (hQvol : volume Q = 1) (a : ℝ) :
    Integrable (cmFactor a (fun _ : Unit => W (Set.indicator Q (fun _ => (1 : ℝ)))) ()) P := by
  have hmap := map_blockIndicator_eq_gaussianReal hW hQm hQvol
  have hmeas : AEMeasurable (W (Set.indicator Q (fun _ => (1 : ℝ)))) P :=
    (hW.meas _ (memLp_blockIndicator hQm hQvol)).aemeasurable
  have hg : Integrable (fun x : ℝ => Real.exp (a * x)) (P.map (W (Set.indicator Q fun _ => 1))) := by
    rw [hmap]
    exact integrable_exp_mul_gaussianReal a
  have hcomp : Integrable
      (fun ω => Real.exp (a * W (Set.indicator Q (fun _ => (1 : ℝ))) ω)) P := by
    have := (integrable_map_measure (by fun_prop) hmeas).mp hg
    exact this
  have hfac : cmFactor a (fun _ : Unit => W (Set.indicator Q (fun _ => (1 : ℝ)))) ()
      = fun ω => Real.exp (-(a ^ 2 / 2)) * Real.exp (a * W (Set.indicator Q fun _ => 1) ω) := by
    funext ω
    rw [cmFactor, ← Real.exp_add]
    ring_nf
  rw [hfac]
  exact hcomp.const_mul _

theorem integral_blockIndicator_cmFactor [IsProbabilityMeasure P]
    {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P) {Q : Set (Space d)}
    (hQm : MeasurableSet Q) (hQvol : volume Q = 1) (a : ℝ) :
    ∫ ω, cmFactor a (fun _ : Unit => W (Set.indicator Q (fun _ => (1 : ℝ)))) () ω ∂P = 1 := by
  have hmap := map_blockIndicator_eq_gaussianReal hW hQm hQvol
  have hmgf : ∫ ω, Real.exp (a * W (Set.indicator Q (fun _ => (1 : ℝ))) ω) ∂P
      = Real.exp (a ^ 2 / 2) := by
    have h := mgf_gaussianReal (X := W (Set.indicator Q (fun _ => (1 : ℝ)))) (p := P)
      (μ := 0) (v := 1) hmap a
    rw [mgf] at h
    simpa using h
  have hfac : ∀ ω, cmFactor a (fun _ : Unit => W (Set.indicator Q (fun _ => (1 : ℝ)))) () ω
      = Real.exp (-(a ^ 2 / 2)) * Real.exp (a * W (Set.indicator Q fun _ => 1) ω) := by
    intro ω
    rw [cmFactor, ← Real.exp_add]
    ring_nf
  simp_rw [hfac]
  rw [integral_const_mul, hmgf, ← Real.exp_add]
  simp

/-- The paper's Step 3 for the white noise read block by block: on an event the exploration
decides, the measure that shifts every block by `a` in the direction of its own indicator
exceeds the unshifted measure by at most `|a|/2` times the square root of a bound for the
expected number of revealed blocks. -/
theorem whiteNoise_block_level_loss (hPin : Sandpile.External.Pinsker)
    [IsProbabilityMeasure P] {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P)
    {ι : Type} [Fintype ι] [DecidableEq ι] (Q : ι → Set (Space d))
    (hQm : ∀ i, MeasurableSet (Q i)) (hQvol : ∀ i, volume (Q i) = 1)
    (hQdisj : ∀ i j, i ≠ j → Disjoint (Q i) (Q j))
    {S : Ω → Finset ι} (hS : IsIndepStoppingSet (fun i => noiseBlockAlg W (Q i)) S)
    (a N : ℝ) (hN : ∫ ω, ((S ω).card : ℝ) ∂P ≤ N)
    {E : Set Ω} (hE : IndepBlockDecides (fun i => noiseBlockAlg W (Q i)) S E) :
    (P.tilted (cmLogDensity a (fun i => W (Set.indicator (Q i) (fun _ => (1 : ℝ))))
      (fun _ : Ω => (Finset.univ : Finset ι)))) E
      ≤ P E + ENNReal.ofReal (|a| / 2 * Real.sqrt N) := by
  refine tilted_cm_measure_le hPin (fun i => noiseBlockAlg_le hW (Q i))
    (iIndep_noiseBlockAlg hW Q hQdisj) hS
    (fun i => W (Set.indicator (Q i) (fun _ => (1 : ℝ)))) ?_ ?_ ?_ a ?_ ?_ N hN hE
  · exact fun i => measurable_noiseBlockAlg_eval (memLp_blockIndicator (hQm i) (hQvol i))
      (fun y hy => Set.indicator_of_notMem hy _)
  · exact fun i => integrable_blockIndicator hW (Q i)
  · exact fun i => hW.mean _ (memLp_blockIndicator (hQm i) (hQvol i))
  · exact fun i => integrable_blockIndicator_cmFactor hW (hQm i) (hQvol i) a
  · exact fun i => integral_blockIndicator_cmFactor hW (hQm i) (hQvol i) a

/-! ### The tilt on one block is the Cameron--Martin shift

`sandpile.tex:2337-2345`: "Let `P_ℓ` be the law obtained by adding the deterministic density
`(ℓ/𝔪)dz` on every unit cube that the rule can reveal ... Since the unit kernel has mass `𝔪`,
the shift raises every field value used by the exploration by `ℓ`."  In one coordinate that
says the exponential tilt by `a x - a²/2` turns the standard Gaussian into the Gaussian of
mean `a`, which is what the next two results prove.
-/

theorem integral_exp_cm_gaussianReal (v : ℝ≥0) (c : ℝ) :
    ∫ x, Real.exp (c * x - c ^ 2 * (v : ℝ) / 2) ∂(gaussianReal 0 v) = 1 := by
  have hfac : ∀ x : ℝ, Real.exp (c * x - c ^ 2 * (v : ℝ) / 2)
      = Real.exp (-(c ^ 2 * (v : ℝ) / 2)) * Real.exp (c * x) := by
    intro x
    rw [← Real.exp_add]
    ring_nf
  simp_rw [hfac]
  rw [integral_const_mul]
  have hm : ∫ x, Real.exp (c * x) ∂(gaussianReal 0 v) = Real.exp ((v : ℝ) * c ^ 2 / 2) := by
    have h := mgf_id_gaussianReal (μ := 0) (v := v)
    have h2 : mgf id (gaussianReal 0 v) c = Real.exp (0 * c + (v : ℝ) * c ^ 2 / 2) := by rw [h]
    rw [mgf] at h2
    simpa using h2
  rw [hm, ← Real.exp_add]
  norm_num
  ring

/-- Cameron--Martin in one dimension: the exponential tilt by `c x - c²v/2` moves the centred
Gaussian of variance `v` to the Gaussian of mean `cv` and the same variance. -/
theorem tilted_gaussianReal_zero (v : ℝ≥0) (hv : v ≠ 0) (c : ℝ) :
    (gaussianReal 0 v).tilted (fun x => c * x - c ^ 2 * (v : ℝ) / 2)
      = gaussianReal (c * (v : ℝ)) v := by
  rw [Measure.tilted, integral_exp_cm_gaussianReal v c]
  simp only [div_one]
  rw [gaussianReal_of_var_ne_zero _ hv, gaussianReal_of_var_ne_zero _ hv,
    ← withDensity_mul _ (measurable_gaussianPDF 0 v)
      (by fun_prop : Measurable fun x : ℝ => ENNReal.ofReal (Real.exp (c * x - c ^ 2 * (v:ℝ) / 2)))]
  congr 1
  funext x
  rw [Pi.mul_apply, gaussianPDF, gaussianPDF, ← ENNReal.ofReal_mul (gaussianPDFReal_nonneg _ _ _)]
  congr 1
  rw [gaussianPDFReal_def, gaussianPDFReal_def]
  simp only
  rw [mul_assoc, ← Real.exp_add]
  congr 2
  have hvpos : (0 : ℝ) < (v : ℝ) := by
    have : v ≠ 0 := hv
    positivity
  field_simp
  ring

/-- The law of the coordinate of a block of volume one under the tilt of that block is the
Gaussian of mean `a`: the tilt of `CrossStoppingSet` is the paper's shift on the block. -/
theorem map_blockIndicator_tilted [IsProbabilityMeasure P] {W : (Space d → ℝ) → Ω → ℝ}
    (hW : IsWhiteNoise d W P) {Q : Set (Space d)} (hQm : MeasurableSet Q)
    (hQvol : volume Q = 1) (a : ℝ) :
    (P.map (W (Set.indicator Q (fun _ => (1 : ℝ))))).tilted (fun x => a * x - a ^ 2 / 2)
      = gaussianReal a 1 := by
  rw [map_blockIndicator_eq_gaussianReal hW hQm hQvol]
  have h := tilted_gaussianReal_zero 1 one_ne_zero a
  simpa using h

/-- The blocks at the unit cells of `ℤ^d`, which are the paper's unit cubes
(`sandpile.tex:2262`: "Tile `ℝ^d` by unit cubes whose centers are in `ℤ^d`").  This is the
form the fixed-scale exploration consumes: the cubes are the cells of the unit mesh, indexed
by distinct integer sites. -/
theorem whiteNoise_cell_level_loss (hPin : Sandpile.External.Pinsker)
    [IsProbabilityMeasure P] {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P)
    {ι : Type} [Fintype ι] [DecidableEq ι] (z : ι → LatticeProb.Site d)
    (hz : Function.Injective z)
    {S : Ω → Finset ι}
    (hS : IsIndepStoppingSet (fun i => noiseBlockAlg W (cell d 1 (z i))) S)
    (a N : ℝ) (hN : ∫ ω, ((S ω).card : ℝ) ∂P ≤ N)
    {E : Set Ω}
    (hE : IndepBlockDecides (fun i => noiseBlockAlg W (cell d 1 (z i))) S E) :
    (P.tilted (cmLogDensity a
        (fun i => W (Set.indicator (cell d 1 (z i)) (fun _ => (1 : ℝ))))
        (fun _ : Ω => (Finset.univ : Finset ι)))) E
      ≤ P E + ENNReal.ofReal (|a| / 2 * Real.sqrt N) :=
  whiteNoise_block_level_loss hPin hW (fun i => cell d 1 (z i))
    (fun i => measurableSet_cell d 1 (z i))
    (fun i => by simpa using volume_cell d one_pos (z i))
    (fun i j hij => cell_disjoint (fun h => hij (hz h))) hS a N hN hE

end Sandpile.Support
