/-
The continuum planar vocabulary of `sandpile.tex:2103-2104` stated on the field
rather than on its law:

  "The unit-scale field `𝒳_1` is stationary, sign-symmetric, invariant under
   rotations by `π/2` and coordinate reflections, and has dependence range 2.
   Finite collections are positively associated by Pitt's Gaussian FKG theorem.
   The fields `𝒳_s` have continuous modifications, … and throughout `𝒳_s`
   denotes that version for every `0<s≤1`."

A field is a function `X : Space 2 → Ω → ℝ` on a probability space, with
measurable coordinates and almost surely continuous sample paths, exactly as the
frozen crossing statements of `Sandpile/Frozen/` carry it.  Its crossing
probabilities are the outer measures of subsets of `Ω`, which is what makes them
non-trivial: `Sandpile/Support/CrossVacuity.lean` records that the same
quantities computed for a law on the space of ALL planar functions are the
number one, whatever the law.

Two predicates.

`IsSymmetricField` is the invariance in law of the field under the group the
paper names: the symmetries of the square lattice of the plane, which are the
translations, the interchange of the two coordinates and the sign changes of the
coordinates (`PlaneSymmetry`, parametrized so that the group law is a single
computation, `PlaneSymmetry.comp`), together with the sign flip of the values.
Equality in law is equality of the pushforwards to the space of planar functions
with its product σ-algebra, which is equality of all finite-dimensional
distributions.

`IsAssociatedField` is positive association of the finite-dimensional
distributions, in the form of Esary, Proschan and Walkup and exactly in the form
Pitt's theorem supplies it: for finitely many points of the plane and bounded
measurable functions of those field values that are nondecreasing in every
coordinate, the two functions correlate nonnegatively.  It is stated on finitely
many points, not on increasing subsets of `Ω`, because that is what the cited
theorem gives; it extends by monotone limits to increasing events depending on
countably many evaluations, which is the class the chain events
`Sandpile.Support.crossApprox` of `Sandpile/Support/CrossUnion.lean` belong to.
The integrals are of bounded measurable functions on a probability space, hence
of integrable functions, so no junk value can arise.
-/
import Sandpile.Support.CrossUnion

open MeasureTheory Set

namespace Sandpile.Continuum

/-- A symmetry of the square lattice of the plane: a permutation of the two
coordinates, a sign on each coordinate, and a translation.  These are the
isometries generated by the translations, the rotations by `π/2` and the
coordinate reflections of `sandpile.tex:2103`. -/
structure PlaneSymmetry where
  /-- The permutation of the two coordinates. -/
  perm : Equiv.Perm (Fin 2)
  /-- The sign attached to each coordinate. -/
  sign : Fin 2 → ℝ
  /-- Each sign is `1` or `-1`. -/
  sign_eq : ∀ k, sign k = 1 ∨ sign k = -1
  /-- The translation part. -/
  shift : Fin 2 → ℝ

namespace PlaneSymmetry

/-- The plane map of a symmetry. -/
noncomputable def toFun (T : PlaneSymmetry) (u : Space 2) : Space 2 :=
  WithLp.toLp 2 (fun k => T.sign k * u (T.perm k) + T.shift k)

theorem toFun_apply (T : PlaneSymmetry) (u : Space 2) (k : Fin 2) :
    T.toFun u k = T.sign k * u (T.perm k) + T.shift k := rfl

/-- The composition of two symmetries, `(T.comp S).toFun = T.toFun ∘ S.toFun`. -/
noncomputable def comp (T S : PlaneSymmetry) : PlaneSymmetry where
  perm := T.perm.trans S.perm
  sign := fun k => T.sign k * S.sign (T.perm k)
  sign_eq := by
    intro k
    rcases T.sign_eq k with h | h <;> rcases S.sign_eq (T.perm k) with h' | h' <;>
      simp [h, h']
  shift := fun k => T.sign k * S.shift (T.perm k) + T.shift k

/-- Translation by `v`. -/
noncomputable def translation (v : Space 2) : PlaneSymmetry where
  perm := Equiv.refl _
  sign := fun _ => 1
  sign_eq := fun _ => Or.inl rfl
  shift := fun k => v k

/-- Interchange of the two coordinates. -/
noncomputable def transpose : PlaneSymmetry where
  perm := Equiv.swap 0 1
  sign := fun _ => 1
  sign_eq := fun _ => Or.inl rfl
  shift := fun _ => 0

/-- Reflection of the first coordinate. -/
noncomputable def reflect : PlaneSymmetry where
  perm := Equiv.refl _
  sign := fun k => if k = 0 then -1 else 1
  sign_eq := by
    intro k
    by_cases h : k = 0 <;> simp [h]
  shift := fun _ => 0

end PlaneSymmetry

/-- The law of the field on the space of planar functions, with its product
σ-algebra: two fields have the same `fieldLaw` exactly when they have the same
finite-dimensional distributions. -/
noncomputable def fieldLaw {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : Space 2 → Ω → ℝ) : Measure (Space 2 → ℝ) :=
  P.map (fun ω u => X u ω)

/-- The field is stationary, sign-symmetric and invariant in law under the
symmetries of the square lattice of the plane (`sandpile.tex:2103-2104`). -/
def IsSymmetricField {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : Space 2 → Ω → ℝ) : Prop :=
  ∀ (T : PlaneSymmetry) (ε : ℝ), (ε = 1 ∨ ε = -1) →
    fieldLaw P (fun u ω => ε * X (T.toFun u) ω) = fieldLaw P X

/-- Positive association of the finite-dimensional distributions of the field,
in the form Pitt's Gaussian FKG theorem supplies (`sandpile.tex:2104`). -/
def IsAssociatedField {Ω : Type*} [MeasurableSpace Ω] (P : Measure Ω)
    (X : Space 2 → Ω → ℝ) : Prop :=
  ∀ (k : ℕ) (q : Fin k → Space 2) (f g : (Fin k → ℝ) → ℝ),
    Monotone f → Monotone g → Measurable f → Measurable g →
    (∃ M : ℝ, ∀ x, |f x| ≤ M) → (∃ M : ℝ, ∀ x, |g x| ≤ M) →
    (∫ ω, f (fun i => X (q i) ω) ∂P) * (∫ ω, g (fun i => X (q i) ω) ∂P)
      ≤ ∫ ω, f (fun i => X (q i) ω) * g (fun i => X (q i) ω) ∂P

end Sandpile.Continuum
