import Sandpile.Support.CrossZeroLimit
import Sandpile.Support.CrossCircuit
import Sandpile.Support.CrossArmIndep
import Sandpile.Support.CrossArmDecay

/-!
# Local measurability of closed superlevel crossing events

This file gives countable representatives `closedCrossEvent` of closed superlevel crossings,
built as a countable intersection of the finite chain events `crossApprox`, and shows they are
measurable from the field restricted to the crossing rectangle alone and agree almost everywhere
with the actual geometric crossing event `Crosses`. This local measurability is what lets the
four-crossing events attached to separated rectangles be shown independent, which is combined
with the FKG-type product bound on a single rectangle to bound the probability of avoiding a
crossing in every one of `n` separated regions.
-/

open MeasureTheory ProbabilityTheory Set Filter Topology
open scoped ENNReal
open Sandpile.Continuum Sandpile.Frozen.FixedScaleCrossings

namespace Sandpile.Support

/-- Chain events need measurable evaluations only inside their rectangle. -/
theorem measurableSet_crossApprox_local {Ω : Type*} [MeasurableSpace Ω]
    (X : Space 2 → Ω → ℝ) (a b : Fin 2 → ℝ) (i : Fin 2) (l : ℝ)
    (hm : ∀ x ∈ rectSet a b, Measurable (X x)) :
    MeasurableSet (crossApprox X a b i l) := by
  classical
  apply MeasurableSet.iUnion
  intro ch
  simp only [pathEvent, setOf_forall]
  refine MeasurableSet.iInter fun j => MeasurableSet.iInter fun q =>
    MeasurableSet.iInter fun hj => MeasurableSet.iInter fun hq0 =>
      MeasurableSet.iInter fun hq1 => ?_
  apply measurableSet_le measurable_const
  apply hm
  apply ch.2.1
  exact Set.mem_biUnion (Finset.mem_range.mpr hj)
    ⟨(q : ℝ), ⟨by exact_mod_cast hq0, by exact_mod_cast hq1⟩, rfl⟩

/-- A measurable representative of the crossing at exactly `l`. -/
noncomputable def closedCrossEvent {Ω : Type*} [MeasurableSpace Ω]
    (X : Space 2 → Ω → ℝ) (a b : Fin 2 → ℝ) (i : Fin 2) (l : ℝ) : Set Ω :=
  ⋂ n : ℕ, crossApprox X a b i (l - 1 / ((n : ℝ) + 1))

/-- `closedCrossEvent` is measurable as soon as `X` is measurable on the rectangle `rectSet a b`,
being a countable intersection of the local `crossApprox` events. -/
theorem measurableSet_closedCrossEvent_local {Ω : Type*} [MeasurableSpace Ω]
    (X : Space 2 → Ω → ℝ) (a b : Fin 2 → ℝ) (i : Fin 2) (l : ℝ)
    (hm : ∀ x ∈ rectSet a b, Measurable (X x)) :
    MeasurableSet (closedCrossEvent X a b i l) :=
  MeasurableSet.iInter fun _ => measurableSet_crossApprox_local X a b i _ hm

/-- The measurable representative `closedCrossEvent` agrees `P`-almost everywhere with the
geometric crossing event `Crosses a b i {x | l ≤ X x ω}`, given a.e. continuity of the field and a
nondegenerate rectangle. -/
theorem closedCrossEvent_ae_eq {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : Space 2 → Ω → ℝ) (a b : Fin 2 → ℝ) (i : Fin 2)
    (hab : ∀ j, a j < b j) (l : ℝ)
    (hc : ∀ᵐ ω ∂P, Continuous fun x => X x ω) :
    closedCrossEvent X a b i l =ᵐ[P] {ω | Crosses a b i {x | l ≤ X x ω}} :=
  (crossing_ae_eq_iInter_crossApprox P X a b i hab l hc).symm

/-- The representative is measurable for the sigma-algebra generated by the
restriction of the field to any region containing the rectangle. -/
theorem measurableSet_closedCrossEvent_comap {Ω : Type*} [MeasurableSpace Ω]
    (X : Space 2 → Ω → ℝ) (a b : Fin 2 → ℝ) (i : Fin 2) (l : ℝ)
    (S : Set (Space 2)) (hS : rectSet a b ⊆ S) :
    MeasurableSet[MeasurableSpace.comap (fun ω (x : S) => X x ω) inferInstance]
      (closedCrossEvent X a b i l) := by
  letI : MeasurableSpace Ω :=
    MeasurableSpace.comap (fun ω (x : S) => X x ω) inferInstance
  apply measurableSet_closedCrossEvent_local
  intro x hx
  have hm : Measurable (fun ω (x : S) => X x ω) := measurable_iff_comap_le.mpr le_rfl
  exact (measurable_pi_apply (⟨x, hS hx⟩ : S)).comp hm

/-- Four genuine closed crossings have the product lower bound, with no loss
of level. The proof passes the chain-event FKG bound to a decreasing limit. -/
theorem closedCrossEvent_four_probability {Ω : Type} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] (X : Space 2 → Ω → ℝ)
    (hm : ∀ x, Measurable (X x)) (ha : IsAssociatedField P X)
    (hc : ∀ᵐ ω ∂P, Continuous fun x => X x ω)
    (a b : Fin 4 → Fin 2 → ℝ) (dir : Fin 4 → Fin 2) (lev : Fin 4 → ℝ)
    (hab : ∀ j k, a j k < b j k) {c : ℝ} (hc0 : 0 ≤ c)
    (hprob : ∀ j, c ≤ P.real {ω | Crosses (a j) (b j) (dir j)
      {x | lev j ≤ X x ω}}) :
    c ^ 4 ≤ P.real (⋂ j, closedCrossEvent X (a j) (b j) (dir j) (lev j)) := by
  let A : ℕ → Set Ω := fun n =>
    ⋂ j, crossApprox X (a j) (b j) (dir j) (lev j - 1 / ((n : ℝ) + 1))
  have hmA : ∀ n, MeasurableSet (A n) := fun n =>
    MeasurableSet.iInter fun j => measurableSet_crossApprox hm _ _ _ _
  have hanti : Antitone A := by
    intro n m hnm ω hω
    apply Set.mem_iInter.mpr
    intro j
    apply crossApprox_mono_level X (a j) (b j) (dir j) _ (Set.mem_iInter.mp hω j)
    exact sub_le_sub_left (one_div_le_one_div_of_le (by positivity)
      (by exact_mod_cast Nat.add_le_add_right hnm 1)) _
  have hp : ∀ n, c ^ 4 ≤ P.real (A n) := by
    intro n
    apply circuit_probability hm ha a b dir _ hc0
    intro j
    apply (hprob j).trans
    apply ENNReal.toReal_mono (measure_ne_top P _)
    exact measure_crossing_le_crossApprox P (hab j 0) (hab j 1) (by positivity) hc
  have hlim := ge_of_tendsto (tendsto_measureReal_iInter A hmA hanti)
    (Eventually.of_forall hp)
  have heq : (⋂ n, A n) = ⋂ j, closedCrossEvent X (a j) (b j) (dir j) (lev j) := by
    ext ω
    simp only [A, closedCrossEvent, mem_iInter]
    exact forall_comm
  rwa [heq] at hlim

/-- Four crossing representatives agree with the four geometric events on a
common event of full probability. -/
theorem four_closedCrossEvent_ae_eq {Ω : Type*} [MeasurableSpace Ω]
    (P : Measure Ω) (X : Space 2 → Ω → ℝ)
    (a b : Fin 4 → Fin 2 → ℝ) (dir : Fin 4 → Fin 2) (lev : Fin 4 → ℝ)
    (hab : ∀ j k, a j k < b j k)
    (hc : ∀ᵐ ω ∂P, Continuous fun x => X x ω) :
    (⋂ j, closedCrossEvent X (a j) (b j) (dir j) (lev j)) =ᵐ[P]
      {ω | ∀ j, Crosses (a j) (b j) (dir j) {x | lev j ≤ X x ω}} := by
  have he := ae_all_iff.mpr fun j => closedCrossEvent_ae_eq P X
    (a j) (b j) (dir j) (hab j) (lev j) hc
  filter_upwards [he] with ω hω
  apply propext
  change (ω ∈ ⋂ j, closedCrossEvent X (a j) (b j) (dir j) (lev j)) ↔ _
  simp only [mem_iInter]
  exact forall_congr' fun j => iff_of_eq (hω j)

/-- Four closed crossings of a continuous associated field have probability
at least the product of their common marginal lower bounds. -/
theorem four_crossing_probability {Ω : Type} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] (X : Space 2 → Ω → ℝ)
    (hm : ∀ x, Measurable (X x)) (ha : IsAssociatedField P X)
    (hc : ∀ᵐ ω ∂P, Continuous fun x => X x ω)
    (a b : Fin 4 → Fin 2 → ℝ) (dir : Fin 4 → Fin 2) (lev : Fin 4 → ℝ)
    (hab : ∀ j k, a j k < b j k) {c : ℝ} (hc0 : 0 ≤ c)
    (hprob : ∀ j, c ≤ P.real {ω | Crosses (a j) (b j) (dir j)
      {x | lev j ≤ X x ω}}) :
    c ^ 4 ≤ P.real {ω | ∀ j, Crosses (a j) (b j) (dir j) {x | lev j ≤ X x ω}} := by
  rw [← measureReal_congr (four_closedCrossEvent_ae_eq P X a b dir lev hab hc)]
  exact closedCrossEvent_four_probability P X hm ha hc a b dir lev hab hc0 hprob

/-- The four-crossing events in separated regions are independent. Their
measurability from the local field is proved, rather than assumed. -/
theorem iIndepSet_four_closedCrossEvent {Ω : Type} [MeasurableSpace Ω]
    {P : Measure Ω} [IsProbabilityMeasure P] {d : ℕ} (hd : d = 2 ∨ d = 3)
    {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P)
    {s : ℝ} (hs : 0 < s) {ι : Type}
    (Reg : ι → Set (Space 2))
    (hsep : ∀ i j, i ≠ j → ∀ u ∈ Reg i, ∀ v ∈ Reg j, 2 * s ≤ ‖u - v‖)
    (a b : ι → Fin 4 → Fin 2 → ℝ) (dir : ι → Fin 4 → Fin 2)
    (lev : ι → Fin 4 → ℝ)
    (hrect : ∀ i j, rectSet (a i j) (b i j) ⊆ Reg i) :
    iIndepSet (fun i => ⋂ j,
      closedCrossEvent (ballField d W s) (a i j) (b i j) (dir i j) (lev i j)) P := by
  apply iIndepSet_ballField_of_separated hd hW hs Reg hsep
  intro i
  exact MeasurableSet.iInter fun j =>
    measurableSet_closedCrossEvent_comap _ _ _ _ _ (Reg i) (hrect i j)

/-- Avoiding four closed crossings in each of `n` separated regions has a
geometric probability bound. The events in the conclusion are the actual
compact connected crossings at the given levels. -/
theorem measure_avoid_four_crossings_le {Ω : Type} [MeasurableSpace Ω]
    (P : Measure Ω) [IsProbabilityMeasure P] {d : ℕ} (hd : d = 2 ∨ d = 3)
    {W : (Space d → ℝ) → Ω → ℝ} (hW : IsWhiteNoise d W P)
    {s : ℝ} (hs : 0 < s)
    (hc : ∀ᵐ ω ∂P, Continuous fun x => ballField d W s x ω)
    (ha : IsAssociatedField P (ballField d W s))
    (Reg : ℕ → Set (Space 2))
    (hsep : ∀ i j, i ≠ j → ∀ u ∈ Reg i, ∀ v ∈ Reg j, 2 * s ≤ ‖u - v‖)
    (a b : ℕ → Fin 4 → Fin 2 → ℝ) (dir : ℕ → Fin 4 → Fin 2)
    (lev : ℕ → Fin 4 → ℝ)
    (hrect : ∀ i j, rectSet (a i j) (b i j) ⊆ Reg i)
    (hab : ∀ i j k, a i j k < b i j k)
    {c : ℝ} (hc0 : 0 ≤ c) (hc1 : c ≤ 1)
    (hprob : ∀ i j, c ≤ P.real {ω | Crosses (a i j) (b i j) (dir i j)
      {x | lev i j ≤ ballField d W s x ω}}) (n : ℕ) :
    P {ω | ∀ i < n, ¬ ∀ j, Crosses (a i j) (b i j) (dir i j)
      {x | lev i j ≤ ballField d W s x ω}} ≤ ENNReal.ofReal ((1 - c ^ 4) ^ n) := by
  let E : ℕ → Set Ω := fun i => ⋂ j,
    closedCrossEvent (ballField d W s) (a i j) (b i j) (dir i j) (lev i j)
  have hm : ∀ x, Measurable (ballField d W s x) :=
    fun x => hW.meas _ (memLp_ballKernel hd hs x)
  have hmE : ∀ i, MeasurableSet (E i) := fun i => MeasurableSet.iInter fun j =>
    measurableSet_closedCrossEvent_local _ _ _ _ _ (fun x _ => hm x)
  have hbound := measure_iInter_compl_le P E hmE
    (iIndepSet_four_closedCrossEvent hd hW hs Reg hsep a b dir lev hrect)
    (c ^ 4) (by positivity) (pow_le_one₀ hc0 hc1)
    (fun i => (ENNReal.ofReal_le_iff_le_toReal (measure_ne_top P _)).2
      (closedCrossEvent_four_probability P _ hm ha hc (a i) (b i) (dir i) (lev i)
        (hab i) hc0 (hprob i))) n
  have he := ae_all_iff.mpr fun i =>
    four_closedCrossEvent_ae_eq P _ (a i) (b i) (dir i) (lev i) (hab i) hc
  have heq : (⋂ i ∈ Finset.range n, (E i)ᶜ) =ᵐ[P]
      {ω | ∀ i < n, ¬ ∀ j, Crosses (a i j) (b i j) (dir i j)
        {x | lev i j ≤ ballField d W s x ω}} := by
    filter_upwards [he] with ω hω
    apply propext
    change (ω ∈ ⋂ i ∈ Finset.range n, (E i)ᶜ) ↔ _
    simp only [mem_iInter, mem_compl_iff, Finset.mem_range]
    exact forall_congr' fun i => forall_congr' fun _ => not_congr (iff_of_eq (hω i))
  rwa [measure_congr heq] at hbound

end Sandpile.Support
