/-
A killed Green field and an exit continuation depend measurably on the
scenery in their domains.  A nearest-neighbor walk exits a cube within one
step of its boundary, so the continuation is measurable in an enlarged cube.
-/
import Sandpile.Support.StoppedOdometer

open MeasureTheory

namespace Sandpile

variable {d : ℕ}

theorem localizedOdometer_congr_domain (hd : 1 ≤ d) (D : Set (Site d))
    (ζ η : Site d → ℝ) (he : ∀ y ∈ D, ζ y = η y) (n : ℕ) :
    localizedOdometer D ζ n = localizedOdometer D η n := by
  induction n with
  | zero => funext x; rw [localizedOdometer_zero hd, localizedOdometer_zero hd]
  | succ n ih =>
    funext x
    by_cases hx : x ∈ D
    · rw [localizedOdometer_succ' hd D ζ n x hx,
        localizedOdometer_succ' hd D η n x hx, he x hx, ih]
    · rw [localizedOdometer_of_notMem D ζ (n + 1) hx,
        localizedOdometer_of_notMem D η (n + 1) hx]

theorem killedKernel_eq_zero_of_target_notMem (D : Set (Site d)) {y : Site d}
    (hy : y ∉ D) (n : ℕ) (x : Site d) : killedKernel D n x y = 0 := by
  classical
  induction n generalizing x with
  | zero =>
    by_cases hx : x ∈ D
    · have hxy : x ≠ y := fun h => hy (h ▸ hx)
      simp [killedKernel, hx, hxy]
    · simp [killedKernel, hx]
  | succ n ih => simp [killedKernel, ih]

theorem killedGreenTime_eq_zero_of_target_notMem (D : Set (Site d)) {y : Site d}
    (hy : y ∉ D) (N : ℕ) (x : Site d) : killedGreenTime D N x y = 0 :=
  Finset.sum_eq_zero fun k _ => killedKernel_eq_zero_of_target_notMem D hy k x

theorem killedGreenPair_congr_domain (D : Set (Site d)) (N : ℕ) (x : Site d)
    (ζ η : Site d → ℝ) (he : ∀ y ∈ D, ζ y = η y) :
    killedGreenPair D N ζ x = killedGreenPair D N η x := by
  refine tsum_congr fun y => ?_
  by_cases hy : y ∈ D
  · rw [he y hy]
  · rw [killedGreenTime_eq_zero_of_target_notMem D hy, zero_mul, zero_mul]

theorem measurable_killedGreenPair (D : Set (Site d)) (N : ℕ) (x : Site d) :
    Measurable (fun ζ : Site d → ℝ => killedGreenPair D N ζ x) := by
  have he : (fun ζ : Site d → ℝ => killedGreenPair D N ζ x) =
      fun ζ => ∑ y ∈ boxFinset x N, killedGreenTime D N x y * ζ y := by
    funext ζ
    refine tsum_eq_sum fun y hy => ?_
    have hz : killedGreenTime D N x y = 0 := by
      by_contra hne
      exact hy (mem_boxFinset (killedGreenTime_support D N x hne))
    rw [hz, zero_mul]
  rw [he]
  exact Finset.measurable_sum _ fun y _ => measurable_const.mul (measurable_pi_apply y)

noncomputable def domainExtend (S : Set (Site d)) (η : S → ℝ) (x : Site d) : ℝ := by
  classical
  exact if hx : x ∈ S then η ⟨x, hx⟩ else 0

theorem measurable_domainExtend (S : Set (Site d)) : Measurable (domainExtend S) := by
  classical
  refine measurable_pi_lambda _ fun x => ?_
  by_cases hx : x ∈ S
  · simpa [domainExtend, hx] using (measurable_pi_apply (⟨x, hx⟩ : S))
  · simp [domainExtend, hx]

/-- A measurable field functional that depends only on a set of coordinates is
measurable for the sigma-algebra generated by their restriction. -/
theorem measurable_restrict_of_congr (S : Set (Site d)) (F : (Site d → ℝ) → ℝ)
    (hFm : Measurable F) (hF : ∀ ζ η, (∀ x ∈ S, ζ x = η x) → F ζ = F η) :
    Measurable[MeasurableSpace.comap (Set.restrict S) inferInstance] F := by
  classical
  have he : F = (F ∘ domainExtend S) ∘ Set.restrict S := by
    funext ζ
    apply hF
    intro x hx
    simp [domainExtend, Set.restrict, hx]
  rw [he]
  exact (hFm.comp (measurable_domainExtend S)).comp (comap_measurable _)

theorem measurable_truncatedExit_site (D : Set (Site d)) (N : ℕ) :
    Measurable (fun X : ℕ → Site d => X (stopBeforeExit D N (fun _ => N) X)) := by
  have hτ : Measurable (stopBeforeExit D N (fun _ : ℕ → Site d => N)) :=
    measurable_const.min (measurable_exitNat D N)
  have heval : Measurable (fun q : (ℕ → Site d) × ℕ => q.1 q.2) :=
    measurable_from_prod_countable_left fun n => measurable_pi_apply n
  exact heval.comp (measurable_id.prodMk hτ)

theorem measurable_uncurry_localizedExitPayoff (hd : 1 ≤ d) (D : Set (Site d)) (N : ℕ)
    (E : Site d → Set (Site d)) (m : ℕ) :
    Measurable (fun p : (Site d → ℝ) × (ℕ → Site d) => localizedExitPayoff D N E m p.1 p.2) := by
  classical
  have hF : Measurable (fun q : (Site d → ℝ) × Site d =>
      if q.2 ∈ D then (0 : ℝ) else localizedOdometer (E q.2) q.1 m q.2) := by
    refine measurable_from_prod_countable_left fun y => ?_
    by_cases hy : y ∈ D
    · simp only [hy, if_pos]; exact measurable_const
    · simp only [if_neg hy]; exact measurable_localizedOdometer hd (E y) m y
  exact hF.comp (measurable_fst.prodMk ((measurable_truncatedExit_site D N).comp measurable_snd))

theorem measurable_integral_localizedExitPayoff (hd : 1 ≤ d) (x : Site d)
    (D : Set (Site d)) (N : ℕ) (E : Site d → Set (Site d)) (m : ℕ) :
    Measurable (fun ζ : Site d → ℝ => ∫ X, localizedExitPayoff D N E m ζ X ∂walkLaw d x) := by
  haveI : NeZero d := ⟨by omega⟩
  exact ((measurable_uncurry_localizedExitPayoff hd D N E m).stronglyMeasurable.integral_prod_right').measurable

/-- A killed field and its exit continuation read only `S` whenever the killed
domain and almost every continuation domain lie in `S`. -/
theorem measurable_killedGreenPair_add_localizedExit_restrict (hd : 1 ≤ d) (x : Site d)
    (D S : Set (Site d)) (N m : ℕ) (E : Site d → Set (Site d)) (hDS : D ⊆ S)
    (hES : ∀ᵐ X ∂walkLaw d x,
      X (stopBeforeExit D N (fun _ => N) X) ∉ D →
        E (X (stopBeforeExit D N (fun _ => N) X)) ⊆ S) :
    Measurable[MeasurableSpace.comap (Set.restrict S) inferInstance]
      (fun ζ : Site d → ℝ => killedGreenPair D N ζ x +
        ∫ X, localizedExitPayoff D N E m ζ X ∂walkLaw d x) := by
  classical
  apply measurable_restrict_of_congr
  · exact (measurable_killedGreenPair D N x).add
      (measurable_integral_localizedExitPayoff hd x D N E m)
  · intro ζ η hζη
    have hb := killedGreenPair_congr_domain D N x ζ η (fun y hy => hζη y (hDS hy))
    rw [hb]
    congr 1
    apply integral_congr_ae
    filter_upwards [hES] with X hX
    change (if X (stopBeforeExit D N (fun _ => N) X) ∈ D then 0 else _) =
      (if X (stopBeforeExit D N (fun _ => N) X) ∈ D then 0 else _)
    split_ifs with hx
    · rfl
    · exact congrFun (localizedOdometer_congr_domain hd _ ζ η
        (fun y hy => hζη y (hX hx hy)) m) _

/-- Almost every walk moves at most one unit in each coordinate at each step. -/
theorem ae_walk_step_boxDist (hd : 1 ≤ d) (x : Site d) :
    ∀ᵐ X ∂walkLaw d x, ∀ n : ℕ, boxDist (X n) (X (n + 1)) ≤ 1 := by
  have hm : MeasurableSet {X : ℕ → Site d | ∀ n : ℕ, boxDist (X n) (X (n + 1)) ≤ 1} := by
    simp only [Set.setOf_forall]
    apply MeasurableSet.iInter
    intro n
    have hp : Measurable (fun X : ℕ → Site d => (X n, X (n + 1))) :=
      (measurable_pi_apply n).prodMk (measurable_pi_apply (n + 1))
    have hb : Measurable (fun X : ℕ → Site d => boxDist (X n) (X (n + 1))) :=
      (measurable_of_countable (fun q : Site d × Site d => boxDist q.1 q.2)).comp hp
    exact measurableSet_le hb measurable_const
  rw [walkLaw, ae_map_iff (measurable_walkPath x).aemeasurable hm]
  filter_upwards [ae_mem_stepSet hd] with ξ hξ n
  have hs : walkPath x ξ (n + 1) = walkPath x ξ n + ξ n := by
    unfold walkPath
    rw [Finset.sum_range_succ, ← add_assoc]
  rw [hs]
  obtain ⟨i, hi | hi⟩ := hξ n
  · rw [hi]; exact boxDist_add_unit _ i
  · rw [hi, ← sub_eq_add_neg]; exact boxDist_sub_unit _ i

theorem boxDist_le_iff_real_coords (x y : Site d) (r : ℕ) :
    boxDist x y ≤ r ↔ ∀ i : Fin d, |(y i : ℝ) - (x i : ℝ)| ≤ r := by
  constructor
  · intro h i
    have hi : (x i - y i).natAbs ≤ r :=
      (Finset.le_sup (f := fun i => (x i - y i).natAbs) (Finset.mem_univ i)).trans h
    have hc : ((x i - y i).natAbs : ℝ) ≤ r := by exact_mod_cast hi
    simpa [natAbs_cast_real, Int.cast_sub, abs_sub_comm] using hc
  · intro h
    refine Finset.sup_le fun i _ => ?_
    have hc : ((x i - y i).natAbs : ℝ) ≤ r := by
      simpa [natAbs_cast_real, Int.cast_sub, abs_sub_comm] using h i
    exact_mod_cast hc

/-- The first exit from a cube is in its one-step enlargement, independently
of the time horizon used to truncate the exit. -/
theorem ae_truncatedExit_cube (hd : 1 ≤ d) (x : Site d) (r N : ℕ) :
    ∀ᵐ X ∂walkLaw d x,
      boxDist x (X (stopBeforeExit {y : Site d | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ r}
        N (fun _ => N) X)) ≤ r + 1 := by
  set D : Set (Site d) := {y | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ r}
  filter_upwards [ae_boxDist_walk hd x, ae_walk_step_boxDist hd x] with X hX hstep
  have h0 : X 0 = x := (boxDist_eq_zero (Nat.eq_zero_of_le_zero (hX 0))).symm
  set k := stopBeforeExit D N (fun _ => N) X
  have hkN : k ≤ N := stopBeforeExit_le (fun _ => le_refl N) X
  by_cases hk : k = 0
  · simp [hk, h0, boxDist_self]
  · have hpre : X (k - 1) ∈ D := by
      apply mem_of_lt_exitNat (t := N)
      · have he : k ≤ exitNat D N X := min_le_right _ _
        omega
      · omega
    have hb : boxDist x (X (k - 1)) ≤ r := (boxDist_le_iff_real_coords _ _ _).mpr hpre
    have hs : boxDist (X (k - 1)) (X k) ≤ 1 := by
      simpa [Nat.sub_add_cancel (Nat.one_le_iff_ne_zero.mpr hk)] using hstep (k - 1)
    exact (boxDist_trans x (X (k - 1)) (X k)).trans (add_le_add hb hs)

theorem cube_killed_continuation_measurable (hd : 1 ≤ d) (x : Site d) (N m : ℕ)
    (A : ℝ) (hA : 1 ≤ A) (r : ℕ) (hr : 1 ≤ r) :
    Measurable[MeasurableSpace.comap
      (Set.restrict {y : Site d | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ (A + 3) * r}) inferInstance]
      (fun ζ : Site d → ℝ =>
        killedGreenPair {y : Site d | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ r} N ζ x +
        ∫ X, localizedExitPayoff {y : Site d | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ r}
          N (fun z => {y : Site d | ∀ i, |(y i : ℝ) - (z i : ℝ)| ≤ A * r}) m ζ X
          ∂walkLaw d x) := by
  apply measurable_killedGreenPair_add_localizedExit_restrict hd
  · intro y hy i
    have hi := hy i
    have hr0 : (0 : ℝ) ≤ r := Nat.cast_nonneg r
    nlinarith
  · filter_upwards [ae_truncatedExit_cube hd x r N] with X hX
    intro _ y hy i
    have hb := (boxDist_le_iff_real_coords _ _ _).mp hX i
    have ht := abs_sub_le (y i : ℝ)
      (X (stopBeforeExit {y : Site d | ∀ i, |(y i : ℝ) - (x i : ℝ)| ≤ r}
        N (fun _ => N) X) i : ℝ) (x i : ℝ)
    have hi := hy i
    have hr1 : (1 : ℝ) ≤ r := by exact_mod_cast hr
    push_cast at hb
    linarith

end Sandpile
