/-
The exit event of a ball, read off the path.

The exit time of a ball is defined by an uncountable infimum, so the event
`{exit time ≤ q}` is not, as it stands, an event of the sigma-algebra generated by
countably many time slices, and nothing about it transfers from one motion to
another.  For a CONTINUOUS path it is, because the path reaches distance `s`
by time `q` exactly when, for every `n`, it is at distance more than `s - 1/(n+1)`
at some RATIONAL time at most `q`: one direction is the density of the rationals
and the continuity of the path, the other is the compactness of `[0,q]` and the
continuity of the norm along the path.

`pathHit` is that countable condition, a measurable subset of the path space
`ℝ≥0 → ℝ^d`, monotone in `q`, and `pathHit_centredPath` identifies it, for the
centred path of a motion with continuous paths, with the event that the motion has
left the ball of radius `s` by time `q`.
-/
import Sandpile.Support.LimPathLaw

open MeasureTheory ProbabilityTheory Filter Topology
open Sandpile.Continuum
open scoped ENNReal NNReal

namespace Sandpile.Support

/-- The paths that reach distance `s` from the origin by time `q`, written as a countable
condition on the values of the path at rational times. -/
def pathHit (d : ℕ) (s : ℝ) (q : ℝ≥0) : Set (ℝ≥0 → Space d) :=
  ⋂ n : ℕ, ⋃ (r : ℚ) (_ : 0 ≤ r) (_ : (r : ℝ) ≤ (q : ℝ)),
    {ξ | s - 1 / (n + 1 : ℝ) < ‖ξ (Real.toNNReal (r : ℝ))‖}

theorem measurableSet_pathHit (d : ℕ) (s : ℝ) (q : ℝ≥0) :
    MeasurableSet (pathHit d s q) := by
  refine MeasurableSet.iInter fun n => ?_
  refine MeasurableSet.iUnion fun r => ?_
  refine MeasurableSet.iUnion fun _ => ?_
  refine MeasurableSet.iUnion fun _ => ?_
  exact measurableSet_lt measurable_const
    ((measurable_pi_apply (Real.toNNReal (r : ℝ))).norm)

theorem pathHit_mono (d : ℕ) (s : ℝ) {q q' : ℝ≥0} (h : q ≤ q') :
    pathHit d s q ⊆ pathHit d s q' := by
  intro ξ hξ
  simp only [pathHit, Set.mem_iInter, Set.mem_iUnion] at hξ ⊢
  intro n
  obtain ⟨r, hr0, hrq, hlt⟩ := hξ n
  exact ⟨r, hr0, le_trans hrq (by exact_mod_cast h), hlt⟩

/-- **The countable condition is the exit event, for a continuous path.** -/
theorem mem_pathHit_iff {d : ℕ} {ξ : ℝ≥0 → Space d} (hξ : Continuous ξ) {s : ℝ}
    (q : ℝ≥0) : ξ ∈ pathHit d s q ↔ ∃ t ≤ q, s ≤ ‖ξ t‖ := by
  have hcont : Continuous fun v : ℝ => ‖ξ (Real.toNNReal v)‖ :=
    (hξ.comp continuous_real_toNNReal).norm
  constructor
  · intro hmem
    simp only [pathHit, Set.mem_iInter, Set.mem_iUnion] at hmem
    choose r hr0 hrq hlt using hmem
    set t : ℕ → ℝ≥0 := fun n => Real.toNNReal ((r n : ℝ)) with ht
    have htmem : ∀ n, t n ∈ Set.Icc (0 : ℝ≥0) q := by
      intro n
      refine ⟨zero_le, ?_⟩
      rw [ht, ← NNReal.coe_le_coe, Real.coe_toNNReal _ (by exact_mod_cast hr0 n)]
      exact hrq n
    obtain ⟨a, ha, φ, hφ, hconv⟩ := (isCompact_Icc (a := (0 : ℝ≥0)) (b := q)).tendsto_subseq htmem
    refine ⟨a, ha.2, ?_⟩
    have h1 : Tendsto (fun k => ‖ξ (t (φ k))‖) atTop (𝓝 ‖ξ a‖) :=
      (hξ.norm.tendsto a).comp hconv
    have h2 : Tendsto (fun k : ℕ => s - 1 / ((φ k : ℝ) + 1)) atTop (𝓝 s) := by
      have hd : Tendsto (fun k : ℕ => 1 / ((φ k : ℝ) + 1)) atTop (𝓝 0) :=
        tendsto_one_div_add_atTop_nhds_zero_nat.comp hφ.tendsto_atTop
      simpa using tendsto_const_nhds.sub hd
    refine le_of_tendsto_of_tendsto h2 h1 ?_
    filter_upwards with k
    exact (hlt (φ k)).le
  · rintro ⟨t, htq, hst⟩
    simp only [pathHit, Set.mem_iInter, Set.mem_iUnion]
    intro n
    have hpos : (0 : ℝ) < 1 / (n + 1 : ℝ) := by positivity
    have hltt : s - 1 / (n + 1 : ℝ) < ‖ξ t‖ := by linarith
    have hU : IsOpen {v : ℝ | s - 1 / (n + 1 : ℝ) < ‖ξ (Real.toNNReal v)‖} :=
      isOpen_lt continuous_const hcont
    have hmemU : (t : ℝ) ∈ {v : ℝ | s - 1 / (n + 1 : ℝ) < ‖ξ (Real.toNNReal v)‖} := by
      show s - 1 / (n + 1 : ℝ) < ‖ξ (Real.toNNReal ((t : ℝ)))‖
      rwa [Real.toNNReal_coe]
    rcases eq_or_lt_of_le (t.coe_nonneg) with h0 | h0
    · have htz : t = 0 := by
        refine NNReal.coe_injective ?_
        simpa using h0.symm
      refine ⟨0, le_rfl, by simp [q.coe_nonneg], ?_⟩
      show s - 1 / (n + 1 : ℝ) < ‖ξ (Real.toNNReal (((0 : ℚ) : ℝ)))‖
      rw [Rat.cast_zero, Real.toNNReal_zero, ← htz]
      exact hltt
    · obtain ⟨δ, hδ, hball⟩ := Metric.isOpen_iff.mp hU _ hmemU
      have hlt' : max 0 ((t : ℝ) - δ / 2) < (t : ℝ) := by
        rcases max_cases (0 : ℝ) ((t : ℝ) - δ / 2) with ⟨h, _⟩ | ⟨h, _⟩
        · rw [h]; exact h0
        · rw [h]; linarith
      obtain ⟨r, hr1, hr2⟩ := exists_rat_btwn hlt'
      have hrge : (0 : ℝ) ≤ (r : ℝ) := le_trans (le_max_left _ _) hr1.le
      have hrδ : (t : ℝ) - δ / 2 ≤ (r : ℝ) := le_trans (le_max_right _ _) hr1.le
      refine ⟨r, by exact_mod_cast hrge, le_trans hr2.le (by exact_mod_cast htq), ?_⟩
      refine hball ?_
      rw [Metric.mem_ball, Real.dist_eq, abs_sub_lt_iff]
      constructor
      · linarith
      · linarith

/-- The centred path of a motion with continuous paths is in `pathHit` exactly when the
motion has left the ball by the given time. -/
theorem mem_pathHit_centredPath {Ω : Type*} {d : ℕ} {B : ℝ≥0 → Ω → Space d} {x : Space d}
    (hc : ∀ ω, Continuous fun t => B t ω) {s : ℝ} (q : ℝ≥0) (ω : Ω) :
    (fun t => B t ω - x) ∈ pathHit d s q ↔
      LatticeProb.exitTime B x s ω ≤ (q : ℝ≥0∞) := by
  have hcξ : Continuous fun t => B t ω - x := by fun_prop
  rw [LatticeProb.exitTime_le_iff hc x s ω q,
    mem_pathHit_iff (ξ := fun t => B t ω - x) hcξ q]

end Sandpile.Support
