import Sandpile.Continuum.WhiteNoise
import LatticeProb.Prob.BrownianMarkov
import Mathlib

/-!
# Brownian motion and the Brownian optimal-stopping value

Brownian motion on `ℝ^d` with generator `Δ/(2d)`, and the Brownian optimal-stopping value of
`sandpile.tex`, `ssec:brownian-stopping` (lines 1069-1110) and `ssec:localization`
(lines 1636-1660):

  `𝒟_h(t,x) = sup_{τ ≤ t} E_x^{BM}[-h(t-τ, B_τ)]`,
  `𝒰_h(t,x) = h(t,x) + 𝒟_h(t,x)`.

How the paper's objects are modelled here:

- Brownian motion is built on Mathlib's real Brownian motion `ProbabilityTheory.IsBrownianReal`:
  a process `B` on `ℝ^d` has generator `Δ/(2d)` and starts at `x` exactly when each coordinate
  of `B - x`, scaled by `√d`, is a real Brownian motion, and the coordinates are independent.
  The scaling is forced by the variance: the generator `Δ/(2d)` gives each coordinate variance
  `t/d` at time `t`. Mathlib 4.32 has no construction of a Brownian motion (Kolmogorov extension
  is not there), so this is a predicate (`IsBrownian`) and every statement below is quantified
  over a space carrying such a process.
- A stopping time (`IsBrownianStopping`) is measurable at every time in the natural filtration
  of `B` (`brownianFiltration`). The ambient measurable space is generated by the full path, so
  the definition does not require a measurable-space argument. When the coordinates of `B` are
  measurable, this is exactly the library's natural-filtration stopping class.
- The value (`brownianValue`) is an `sSup` over the reals attained by admissible stopping times.
  The set is nonempty, since `τ = 0` is admissible.
- The ball-localized value `𝒰_{Z,A}` (`brownianValueBall`) of `ssec:localization` replaces each
  `τ` by `τ ∧ τ_{u,A}`, the exit time of the Euclidean ball of radius `A` about `u`; here that is
  the same supremum over the stopping times which have not left the ball strictly before they
  stop.
-/

open MeasureTheory ProbabilityTheory
open scoped NNReal ENNReal

namespace Sandpile.Continuum

/-- `B` is Brownian motion on `ℝ^d` with generator `Δ/(2d)` started at `x`. -/
structure IsBrownian {Ω : Type*} [MeasurableSpace Ω] (d : ℕ) (x : Space d)
    (B : ℝ≥0 → Ω → Space d) (P : Measure Ω) : Prop where
  /-- The process starts at `x`. -/
  start : ∀ᵐ ω ∂P, B 0 ω = x
  /-- Each coordinate, centred and scaled by `√d`, is a real Brownian motion. -/
  coord : ∀ i : Fin d, IsBrownianReal (fun t ω => Real.sqrt d * (B t ω i - x i)) P
  /-- The coordinate processes are independent. -/
  indep : iIndepFun (fun (i : Fin d) (ω : Ω) => fun t : ℝ≥0 => B t ω i) P

/-- The natural filtration of the process, on the measurable space generated by its full path. -/
noncomputable def brownianFiltration {Ω : Type*} {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) :
    Filtration ℝ≥0 (MeasurableSpace.comap (fun ω => fun t => B t ω) inferInstance) := by
  letI : MeasurableSpace Ω :=
    MeasurableSpace.comap (fun ω => fun t => B t ω) inferInstance
  have hp : Measurable (fun ω => fun t => B t ω) := measurable_iff_comap_le.mpr le_rfl
  exact Filtration.natural B fun t => ((measurable_pi_apply t).comp hp).stronglyMeasurable

/-- A finite stopping time of the motion's natural filtration. -/
def IsBrownianStopping {Ω : Type*} {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) (τ : Ω → ℝ≥0) : Prop :=
  IsStoppingTime (Sandpile.Continuum.brownianFiltration B) fun ω => (τ ω : ℝ≥0∞)

/-- The natural stopping class agrees with the library's class whenever the coordinates
are strongly measurable in the ambient measurable space. -/
theorem isBrownianStopping_iff_natFiltration
    {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) (hm : ∀ t, StronglyMeasurable (B t))
    (τ : Ω → ℝ≥0) :
    Sandpile.Continuum.IsBrownianStopping B τ ↔
      IsStoppingTime (LatticeProb.natFiltration B hm) (fun ω => (τ ω : ℝ≥0∞)) := Iff.rfl

/-- A deterministic time is a Brownian stopping time. -/
theorem isBrownianStopping_const {Ω : Type*} {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) (t : ℝ≥0) :
    Sandpile.Continuum.IsBrownianStopping B (fun _ => t) := by
  exact isStoppingTime_const (Sandpile.Continuum.brownianFiltration B) t

/-- Natural-filtration stopping times satisfy the pointwise history criterion. -/
theorem IsBrownianStopping.galmarino {Ω : Type*} {d : ℕ}
    {B : ℝ≥0 → Ω → Sandpile.Continuum.Space d} {τ : Ω → ℝ≥0}
    (hτ : Sandpile.Continuum.IsBrownianStopping B τ) (t : ℝ≥0) (ω ω' : Ω)
    (ht : τ ω = t) (hp : ∀ s ≤ t, B s ω = B s ω') : τ ω' = t := by
  have he := MeasureTheory.IsStoppingTime.measurableSet_eq hτ t
  rw [Sandpile.Continuum.brownianFiltration, Filtration.natural_eq_comap] at he
  rcases he with ⟨S, _hS, he⟩
  have hh : (fun s : Set.Iic t => B s ω) = (fun s : Set.Iic t => B s ω') :=
    funext fun s => hp s s.property
  have hw : (fun s : Set.Iic t => B s ω) ∈ S := by
    change ω ∈ (fun ω (s : Set.Iic t) => B s ω) ⁻¹' S
    rw [he]
    exact congrArg (fun s : ℝ≥0 => (s : ℝ≥0∞)) ht
  have hw' : ω' ∈ (fun ω (s : Set.Iic t) => B s ω) ⁻¹' S := by
    change (fun s : Set.Iic t => B s ω') ∈ S
    rwa [← hh]
  rw [he] at hw'
  exact ENNReal.coe_inj.1 hw'

/-- Every past coordinate is measurable in the current natural filtration. -/
theorem measurable_brownianFiltration {Ω : Type*} {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) (s t : ℝ≥0) (hst : s ≤ t) :
    @Measurable Ω (Sandpile.Continuum.Space d) (Sandpile.Continuum.brownianFiltration B t)
      inferInstance (B s) := by
  exact measurable_iff_comap_le.2 (le_iSup_of_le s (le_iSup_of_le hst le_rfl))

/-- The natural filtration is generated by the past coordinates. -/
theorem brownianFiltration_le {Ω : Type*} {d : ℕ}
    (B : ℝ≥0 → Ω → Sandpile.Continuum.Space d) (t : ℝ≥0) (m : MeasurableSpace Ω)
    (hm : ∀ s ≤ t, @Measurable Ω (Sandpile.Continuum.Space d) m inferInstance (B s)) :
    Sandpile.Continuum.brownianFiltration B t ≤ m := by
  exact iSup₂_le fun s hs => (hm s hs).comap_le

/-- `𝒟_h(t,x) = sup_{τ ≤ t} E_x^{BM}[-h(t-τ, B_τ)]`. -/
noncomputable def brownianDiscount {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (B : ℝ≥0 → Ω → Space d) (P : Measure Ω) (h : ℝ → Space d → ℝ) (t : ℝ) : ℝ :=
  sSup {a : ℝ | ∃ τ : Ω → ℝ≥0, IsBrownianStopping B τ ∧ (∀ ω, (τ ω : ℝ) ≤ t) ∧
    a = ∫ ω, -h (t - τ ω) (B (τ ω) ω) ∂P}

/-- `𝒰_h(t,x) = h(t,x) + 𝒟_h(t,x)`. -/
noncomputable def brownianValue {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (B : ℝ≥0 → Ω → Space d) (P : Measure Ω) (h : ℝ → Space d → ℝ)
    (t : ℝ) (x : Space d) : ℝ :=
  h t x + brownianDiscount B P h t

/-- `𝒟_{h,A}` at `u`: the same supremum, over stopping times which have not left
the Euclidean ball of radius `A` about `u` strictly before stopping. -/
noncomputable def brownianDiscountBall {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (B : ℝ≥0 → Ω → Space d) (P : Measure Ω) (h : ℝ → Space d → ℝ)
    (t A : ℝ) (u : Space d) : ℝ :=
  sSup {a : ℝ | ∃ τ : Ω → ℝ≥0, IsBrownianStopping B τ ∧ (∀ ω, (τ ω : ℝ) ≤ t) ∧
    (∀ᵐ ω ∂P, ∀ s : ℝ≥0, s < τ ω → ‖B s ω - u‖ ≤ A) ∧
    a = ∫ ω, -h (t - τ ω) (B (τ ω) ω) ∂P}

/-- `𝒰_{h,A}(t,u)`, the ball-localized value. -/
noncomputable def brownianValueBall {Ω : Type*} [MeasurableSpace Ω] {d : ℕ}
    (B : ℝ≥0 → Ω → Space d) (P : Measure Ω) (h : ℝ → Space d → ℝ)
    (t A : ℝ) (u : Space d) : ℝ :=
  h t u + brownianDiscountBall B P h t A u

end Sandpile.Continuum
