"""Produce the Lean certificate: a machine-checked record of what is proved.

The certificate is not prose.  Every line of it is generated by running the
checkers and by asking Lean itself for each theorem's axiom closure, so a reader
can reproduce it with the commands it names and compare byte for byte.

    python3 tools/certificate.py            # write CERTIFICATE.md
    python3 tools/certificate.py --check    # verify the file on disk is current
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("certificate.py: PyYAML is required (pip install pyyaml)")

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "ledger" / "manifest.yaml"
OUT = ROOT / "CERTIFICATE.md"
ELAN = str(Path.home() / ".elan" / "bin")

# The three axioms of Lean's own logic.  Anything else in a closure -- above all
# `sorryAx` -- means the statement is not proved.
CLASSICAL = {"propext", "Classical.choice", "Quot.sound"}


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    import os
    env = {**os.environ, "PATH": ELAN + ":" + os.environ.get("PATH", "")}
    return subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True, env=env, **kw)


def axiom_lines(exports: list[str]) -> dict[str, str]:
    """Ask Lean for each export's axiom closure, in one elaboration."""
    imports = sorted({f"import {m}" for m in ("Sandpile.Basic",)} |
                     {f"import {p}" for p in module_names()})
    src = "\n".join(imports) + "\n" + "\n".join(f"#print axioms {e}" for e in exports) + "\n"
    probe = ROOT / "scratch" / "_certificate_probe.lean"
    probe.parent.mkdir(exist_ok=True)
    probe.write_text(src, encoding="utf-8")
    try:
        r = run(["lake", "env", "lean", str(probe)], timeout=3600)
    finally:
        probe.unlink(missing_ok=True)
    out: dict[str, str] = {}
    # Lean wraps a long axiom list across lines, so match over the whole output, not line by line.
    for m in re.finditer(r"'([^']+)' (?:depends on axioms: \[(.*?)\]|does not depend on any axioms)",
                         r.stdout, re.S):
        out[m.group(1)] = " ".join((m.group(2) or "").split())
    missing = [e for e in exports if e not in out]
    if missing:
        # An export with no reported closure is an error, never a clean verdict.
        raise RuntimeError("certificate: no axiom report for " + ", ".join(missing) + "\n" + r.stdout[-2000:] + r.stderr[-2000:])
    return out


def module_names() -> list[str]:
    names = []
    for f in sorted((ROOT / "Sandpile").rglob("*.lean")):
        names.append(str(f.relative_to(ROOT).with_suffix("")).replace("/", "."))
    return names


def frozen_hash(node: dict) -> str:
    text = (ROOT / node["file"]).read_text(encoding="utf-8")
    b = text[text.index("-- FROZEN-STATEMENT-BEGIN") + len("-- FROZEN-STATEMENT-BEGIN"):
             text.index("-- FROZEN-STATEMENT-END")]
    if b.startswith("\n"):
        b = b[1:]
    return hashlib.sha256(b.encode("utf-8")).hexdigest()


def build() -> str:
    manifest = yaml.safe_load(MANIFEST.read_text(encoding="utf-8"))
    nodes = manifest["nodes"]
    exports = [n["export"] for n in nodes]

    r = run(["lake", "build", "Sandpile"], timeout=7200)
    jobs = re.search(r"Build completed successfully \((\d+) jobs\)", r.stdout)
    build_ok = r.returncode == 0
    warnings = [l for l in r.stdout.splitlines() if l.startswith("warning:")]

    ax = axiom_lines(exports)
    toolchain = (ROOT / "lean-toolchain").read_text().strip()
    mlmanifest = yaml.safe_load("{}")
    packages = json.loads((ROOT / "lake-manifest.json").read_text(encoding="utf-8"))["packages"]
    ml_rev = next((p["rev"] for p in packages if p["name"] == "mathlib"), None)
    paper = ROOT / "paper" / "sandpile.tex"
    paper_sha = hashlib.sha256(paper.read_bytes()).hexdigest()

    lines: list[str] = []
    A = lines.append
    A("# Lean certificate")
    A("")
    A("*Quantitative explosion and percolation of the divisible sandpile*,")
    A("Bou-Rabee–Panagiotis.  This file records what a machine has checked, and how")
    A("to check it again.  It is generated by `python3 tools/certificate.py`; do not")
    A("edit it by hand.")
    A("")
    A("## What is claimed")
    A("")
    # The counts come from the manifest, so this paragraph cannot drift from it.
    _paper = [n for n in nodes if not n["file"].startswith("Sandpile/External/")]
    _ext = [n for n in nodes if n["file"].startswith("Sandpile/External/")]
    _assumed = [n for n in _ext if n["state"] == "FROZEN"]
    A(f"Every theorem, lemma, proposition and corollary of the paper is stated in")
    A(f"Lean 4: {len(_paper)} nodes, all `SEALED`, proved from Mathlib and the shared")
    A(f"library Lattice-Probability.  No node contains a `sorry` and none adds an")
    A(f"axiom.")
    A("")
    A(f"The development is NOT unconditional.  {len(_ext)} further nodes state results the")
    A(f"paper quotes from other papers; {len(_assumed)} of them are assumed, each carried as an")
    A(f"explicit hypothesis by the theorems that use it, and the rest are proved here.")
    A("The theorems below are therefore proved modulo those hypotheses, which are")
    A("listed with their statements in `ASSUMPTIONS.md`.")
    A("")
    A("## Environment")
    A("")
    A("| | |")
    A("|---|---|")
    A(f"| Lean toolchain | `{toolchain}` |")
    A(f"| Mathlib revision | `{ml_rev or 'unknown'}` |")
    A(f"| Paper (`paper/sandpile.tex`) SHA-256 | `{paper_sha}` |")
    A(f"| Build | {'succeeded' if build_ok else 'FAILED'}"
      f"{f', {jobs.group(1)} jobs' if jobs else ''} |")
    A(f"| Build warnings | {len(warnings)} |")
    A(f"| Generated | {date.today().isoformat()} |")
    A("")
    A("## Reproducing it")
    A("")
    A("```")
    A("elan toolchain install $(cat lean-toolchain)")
    A("lake exe cache get      # optional: prebuilt Mathlib")
    A("lake build Sandpile")
    A("python3 tools/check_manifest.py     # frozen statements match their hashes")
    A("python3 tools/check_axioms.py       # no axiom closure contains sorryAx")
    A("python3 tools/check_warnings.py     # the build emits no unauthorized warning")
    A("python3 tools/check_coverage.py     # every paper statement is formalized")
    A("python3 tools/certificate.py --check")
    A("```")
    A("")
    A("## The theorems, and what each depends on")
    A("")
    A("`#print axioms` reports the full transitive axiom closure of a proof.  A")
    A("closure of exactly `propext, Classical.choice, Quot.sound` is classical")
    A("mathematics and nothing more; those three are Lean's own, not ours.")
    A("`sorryAx` in a closure would mean the statement is not proved.  It appears")
    A("nowhere below.")
    A("")
    A("| # | node | Lean name | paper | axioms |")
    A("|---|---|---|---|---|")
    clean = 0
    for i, n in enumerate(nodes, 1):
        e = n["export"]
        got = {a.strip() for a in ax.get(e, "").split(",") if a.strip()}
        extra = got - CLASSICAL
        verdict = "classical only" if not extra else "**" + ", ".join(sorted(extra)) + "**"
        if not extra:
            clean += 1
        src = n["source"]
        m = re.search(r"label ([A-Za-z][A-Za-z0-9:_-]*)", src)
        paper_cell = f"`{m.group(1)}`" if m else "—"
        A(f"| {i} | `{n['id']}` | `{e}` | {paper_cell} | {verdict} |")
    A("")
    A(f"{clean} of {len(nodes)} nodes depend on nothing beyond the three classical")
    n_sealed = sum(1 for n in nodes if n["state"] == "SEALED")
    n_frozen = sum(1 for n in nodes if n["state"] == "FROZEN")
    A(f"axioms.  In `ledger/manifest.yaml`, {n_sealed} nodes are `SEALED` and {n_frozen} are")
    A("`FROZEN` (the assumed cited results).")
    A("")
    A("## Frozen statements")
    A("")
    A("The bytes of each statement are pinned, so a statement cannot be weakened")
    A("after the fact without the hash changing.  `tools/check_manifest.py`")
    A("verifies these; the recipe is in `CORRESPONDENCE.md`.")
    A("")
    A("| node | SHA-256 of the frozen statement |")
    A("|---|---|")
    for n in nodes:
        h = frozen_hash(n)
        flag = "" if h == n["frozen_sha256"] else "  ← MISMATCH"
        A(f"| `{n['id']}` | `{h}`{flag} |")
    A("")
    A("## What is not claimed")
    A("")
    A("- The paper's open questions (Section 7) are questions; nothing there is")
    A("  formalized, and nothing here bears on them.")
    A("- The figures, the simulations and the survey in Section 1.4 are outside")
    A("  the formalization.")
    A("")
    return "\n".join(lines) + "\n"


def main() -> int:
    text = build()
    if "--check" in sys.argv[1:]:
        if not OUT.exists():
            print("certificate: CERTIFICATE.md is missing", file=sys.stderr)
            return 1
        cur = OUT.read_text(encoding="utf-8")
        # the generation date is allowed to differ
        strip = lambda s: re.sub(r"\| Generated \| .* \|", "", s)
        if strip(cur) != strip(text):
            print("certificate: CERTIFICATE.md is out of date; regenerate it",
                  file=sys.stderr)
            return 1
        print("certificate: OK (CERTIFICATE.md matches the checked state)")
        return 0
    OUT.write_text(text, encoding="utf-8")
    print(f"certificate: wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
